- .circleci/config.yml
- README.md
- data/examples/declaration/data/deriving-strategies-out.hs
- data/examples/declaration/data/deriving-strategies.hs
- data/examples/declaration/data/gadt/multiline-out.hs
- data/examples/declaration/data/multiline-arg-parens-out.hs
- data/examples/declaration/data/multiline-out.hs
- data/examples/declaration/data/multiline.hs
- data/examples/declaration/data/simple-broken-out.hs
- data/examples/declaration/type-families/closed-type-family/multi-line-out.hs
- default.nix
- nix/nixpkgs/default.nix
- ormolu.cabal
- src/Ormolu/Imports.hs
- src/Ormolu/Printer/Combinators.hs
- src/Ormolu/Printer/Comments.hs
- src/Ormolu/Printer/Meat/Declaration.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
- src/Ormolu/Printer/Meat/Declaration/Pat.hs
- src/Ormolu/Printer/Meat/Declaration/Signature.hs
- src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
- src/Ormolu/Printer/Meat/ImportExport.hs
- src/Ormolu/Printer/Meat/Module.hs
- src/Ormolu/Printer/Meat/Type.hs
> Nix-powered builds and switch to GHC 8.6.4

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
> Add ‘CONTRIBUTING.md’ file to the repository

- data/examples/declaration/value/function/do-out.hs
- data/examples/declaration/value/function/do.hs
- data/examples/declaration/value/function/if-multi-line-out.hs
- data/examples/declaration/value/function/if-multi-line.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Fix rendering of hanging constructions

- data/examples/declaration/value/function/case-multi-line-out.hs
- data/examples/declaration/value/function/case-multi-line.hs
- data/examples/declaration/value/function/if-multi-line-out.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
Also rolls back handing things in if branches, because it doesn't look so good?
cc @facundominguez
> Fix rendering of case alternatives with guards

- data/examples/declaration/instance/associated-types-out.hs
- data/examples/declaration/instance/type-family-instances-out.hs
- data/examples/declaration/type-families/closed-type-family/infix-out.hs
- data/examples/declaration/type-families/closed-type-family/infix.hs
- data/examples/declaration/type-families/closed-type-family/multi-line-out.hs
- data/examples/declaration/value/function/backticks-out.hs
- data/examples/declaration/value/function/backticks.hs
- data/examples/declaration/value/function/infix-out.hs
- data/examples/declaration/value/function/infix.hs
- src/Ormolu/Printer/Meat/Common.hs
- src/Ormolu/Printer/Meat/Declaration/Instance.hs
- src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Fix rendering of infix constructions in lhs of definitions

- data/examples/declaration/value/function/n-plus-k-pattern-out.hs
- data/examples/declaration/value/function/n-plus-k-pattern.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Implement n+k pattern

- data/examples/declaration/role-annotation/simple-out.hs
- data/examples/declaration/role-annotation/simple.hs
- ormolu.cabal
- src/Ormolu/Printer/Meat/Declaration.hs
- src/Ormolu/Printer/Meat/Declaration/RoleAnnotation.hs
> Support rendering of role annotation declarations

- data/examples/declaration/signature/minimal/minimal-out.hs
- data/examples/declaration/signature/minimal/minimal.hs
- data/examples/module-header/warning-pragma-list-multiline-out.hs
- data/examples/module-header/warning-pragma-list-multiline.hs
- data/examples/module-header/warning-pragma-multiline-out.hs
- data/examples/module-header/warning-pragma-multiline.hs
- data/examples/module-header/warning-pragma-out.hs
- data/examples/module-header/warning-pragma-singleton-list-out.hs
- data/examples/module-header/warning-pragma-singleton-list.hs
- data/examples/module-header/warning-pragma.hs
- src/Ormolu/Imports.hs
- src/Ormolu/Printer/Combinators.hs
- src/Ormolu/Printer/Comments.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
- src/Ormolu/Printer/Meat/Declaration/Signature.hs
- src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
- src/Ormolu/Printer/Meat/Module.hs
- src/Ormolu/Utils.hs
This is part of #70
This is based off of #103 in order to use the latest pragma combinator.
> Add MinimalSig printer

- data/examples/declaration/default/default-out.hs
- data/examples/declaration/default/default.hs
- ormolu.cabal
- src/Ormolu/Printer/Meat/Declaration.hs
- src/Ormolu/Printer/Meat/Declaration/Default.hs
> Add Default declaration printer

- data/examples/declaration/signature/complete/complete-out.hs
- data/examples/declaration/signature/complete/complete.hs
- src/Ormolu/Printer/Meat/Declaration/Signature.hs
This is part of #70
This is based off of #103 in order to use the latest pragma combinator.
> Add CompleteMatchSig printer

- data/examples/declaration/annotation/annotation-out.hs
- data/examples/declaration/annotation/annotation.hs
- data/examples/declaration/value/function/explicit-type-out.hs
- data/examples/declaration/value/function/explicit-type.hs
- data/examples/declaration/value/function/pattern/splice-pattern-out.hs
- data/examples/declaration/value/function/pattern/splice-pattern.hs
- ormolu.cabal
- src/Ormolu/Anns.hs
- src/Ormolu/Printer/Meat/Declaration.hs
- src/Ormolu/Printer/Meat/Declaration/Annotation.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
This is part of #70
This is based off of #103 in order to use the latest `pragma` combinator.
> Add AnnD printer

- data/examples/declaration/foreign/foreign-export-out.hs
- data/examples/declaration/foreign/foreign-export.hs
- data/examples/declaration/foreign/foreign-import-out.hs
- data/examples/declaration/foreign/foreign-import.hs
- ormolu.cabal
- src/Ormolu/Printer/Meat/Declaration.hs
- src/Ormolu/Printer/Meat/Declaration/Foreign.hs
> [#53] Implement rendering for foreign declarations

- data/examples/declaration/signature/set-cost-centre/set-cost-centre-out.hs
- data/examples/declaration/signature/set-cost-centre/set-cost-centre.hs
- src/Ormolu/Printer/Meat/Declaration.hs
- src/Ormolu/Printer/Meat/Declaration/Signature.hs
Part of #70 
- added test (is multiline necessary?)
- extended `p_sigDecl'` to handle SCC
> [#70] implemented set cost centre

- data/examples/declaration/value/function/guards-out.hs
- data/examples/declaration/value/function/guards.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
Fixes https://github.com/tweag/ormolu/issues/124
> Allegedly fix function guards

- data/examples/declaration/value/function/equality-constraints-out.hs
- data/examples/declaration/value/function/equality-constraints.hs
- src/Ormolu/Printer/Meat/Common.hs
Close #126.
Please see the comment in the diff.
> Fix rendering of type equalities

- data/examples/import/qualified-prelude-out.hs
- data/examples/import/qualified-prelude.hs
- src/Ormolu/Imports.hs
> Fix comparison of prelude imports

- data/examples/declaration/value/function/lambda-single-line-out.hs
- data/examples/declaration/value/function/lambda-single-line.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
Fixes #144
It will probably take more time for you to review than doing it yourself, but I'd appreciate any feedback if this is not the fix you intended.
> Keep space in lambdas with lazyness annotation

- data/examples/other/trailing-whitespace-out.hs
- data/examples/other/trailing-whitespace.hs
- src/Ormolu/Parser/CommentStream.hs
> Implement dropping of trailing whitespace in comments

- data/examples/declaration/splice/quotes-out.hs
- data/examples/declaration/splice/quotes.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
Somehow this was missing and made Ormolu choke on some files.
> Implement ‘VarBr’

- data/examples/declaration/value/function/typed-hole-out.hs
- data/examples/declaration/value/function/typed-hole.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Backticked typed holes

- data/examples/declaration/value/function/lambda-single-line-out.hs
- data/examples/declaration/value/function/lambda-single-line.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Bang patterns and splices in lambdas

- data/examples/declaration/signature/specialize/specialize-out.hs
- data/examples/declaration/signature/specialize/specialize.hs
- src/Ormolu/Printer/Meat/Declaration/Signature.hs
> Comma-separated SPECIALIZE types

- src/Ormolu/Parser.hs
> Blacklist extensions instead of whitelisting them

- data/examples/declaration/value/function/arithmetic-sequences-out.hs
- data/examples/declaration/value/function/arithmetic-sequences.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Insert space before double dot of arithmetic sequence and add some examples to check it.

- data/examples/declaration/data/deriving-out.hs
- data/examples/declaration/data/deriving-strategies-out.hs
- data/examples/declaration/data/deriving.hs
- data/examples/declaration/data/multiline-arg-parens-out.hs
- data/examples/declaration/data/simple-broken-out.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
> Surround deriving with parenthes everywhere

- data/examples/declaration/value/function/negation-out.hs
- data/examples/declaration/value/function/negation.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> [#181] add space after -

- data/examples/declaration/signature/type/infix-promoted-type-constructor-out.hs
- src/Ormolu/Printer/Meat/Common.hs
> Preserve operators promotion (single quote)

- data/examples/declaration/data/gadt/multiple-declaration-out.hs
- data/examples/declaration/data/gadt/multiple-declaration.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
> [#188] Keep comma on multiple GADT declaration

- data/examples/declaration/value/function/where-out.hs
- data/examples/declaration/value/function/where.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Preserve empty where clause

- data/examples/declaration/splice/quotes-out.hs
- data/examples/declaration/splice/quotes.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Fix parentheses around TH-quoted operators

- data/examples/declaration/value/function/let-multi-line-out.hs
- data/examples/declaration/value/function/let-multi-line.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Handle inline comments before let correctly

- data/examples/declaration/type/promotion-out.hs
- data/examples/declaration/type/promotion.hs
- src/Ormolu/Printer/Combinators.hs
- src/Ormolu/Printer/Meat/Type.hs
Fixes #184 
Thanks @gabrielelana !
> [#184] Handle promoted types

- data/examples/declaration/type/misc-kind-signatures-out.hs
- data/examples/declaration/type/misc-kind-signatures.hs
- src/Ormolu/Printer/Meat/Type.hs
> Always put parens around kind signatures

- data/examples/declaration/value/pattern-synonyms/unidirectional-out.hs
- data/examples/declaration/value/pattern-synonyms/unidirectional.hs
- src/Ormolu/Printer/Meat/Declaration.hs
> Don't separate pattern signature from pattern (fixes #192)

- data/examples/module-header/double-dot-with-names-out.hs
- data/examples/module-header/double-dot-with-names.hs
- src/Ormolu/Printer/Meat/Common.hs
- src/Ormolu/Printer/Meat/ImportExport.hs
Close #190.
Credit to @exw for pairing with me on this!
> Better export list formatting (fixes #190)

- data/examples/declaration/signature/inline/conlike-out.hs
- data/examples/declaration/signature/inline/conlike.hs
- src/Ormolu/Printer/Meat/Declaration/Signature.hs
> Add support for the CONLIKE modifier in inlining pragmas

- data/examples/declaration/value/function/pattern/unboxed-sum-pattern-out.hs
- data/examples/declaration/value/function/pattern/unboxed-sum-pattern.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Format unboxed sum pattern

- data/examples/declaration/value/function/unboxed-string-lit-out.hs
- data/examples/declaration/value/function/unboxed-string-lit.hs
- ormolu.cabal
- src/Ormolu/Diff.hs
> Avoid crashing on unboxed string literals

- data/examples/declaration/type/splice-out.hs
- data/examples/declaration/type/splice.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs-boot
- src/Ormolu/Printer/Meat/Type.hs
> Add printer for HsSpliceTy

- data/examples/declaration/value/function/lambda-multi-line-out.hs
- data/examples/declaration/value/function/lambda-multi-line.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Fine-tune placement of lambdas after operators

- data/examples/other/following-comment-last-0-out.hs
- data/examples/other/following-comment-last-0.hs
- data/examples/other/following-comment-last-1-out.hs
- data/examples/other/following-comment-last-1.hs
- data/examples/other/following-comment-last-2-out.hs
- data/examples/other/following-comment-last-2.hs
- data/examples/other/following-comment-last-3-out.hs
- data/examples/other/following-comment-last-3.hs
- src/Ormolu/Printer/Meat/Module.hs
Close #186.
I was wresting with this one for a while. Will finish later.
> Make sure no comments are swallowed at the end

- data/examples/declaration/instance/contexts-out.hs
- data/examples/declaration/value/function/operators-out.hs
- data/examples/declaration/value/function/operators.hs
- data/examples/other/argument-comment-out.hs
- data/examples/other/argument-comment.hs
- src/Ormolu/Printer/Comments.hs
> Fix mis-formatting of per-argument comments in certain cases

- data/examples/declaration/value/function/block-arguments-out.hs
- data/examples/declaration/value/function/block-arguments.hs
@mitchellwrosen I added some cases involving hanging lambdas.
> Add a couple of tests for lambdas with block arguments

- data/examples/declaration/value/function/multi-way-if-out.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Change MultiWayIf layout to keep consistent 2-space indent increase

- app/Main.hs
> Support formatting multiple files at once

- data/examples/declaration/value/function/lambda-multi-line1-out.hs
- data/examples/declaration/value/function/lambda-multi-line1.hs
- data/examples/declaration/value/function/lambda-multi-line2.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Align lambda arguments

- src/Ormolu.hs
Related: #355.
Turns out when `--unsafe` is not set, exceptions thrown in formatting code are catched in the subsequent parsing check, which wraps them as GHC errors adding a text like:
```
Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```
Which is misleading since the error is not caused by GHC.
This PR avoids it by strictly binding the result of `printModule`.
> Don't wrap Ormolu exceptions as GHC errors

- data/examples/module-header/shebang-out.hs
- data/examples/module-header/shebang.hs
- src/Ormolu/Parser.hs
> Fix positioning of shebangs

- data/examples/declaration/value/function/infix/applicative.hs
- data/examples/declaration/value/function/infix/comments-out.hs
- data/examples/declaration/value/function/infix/dollar-chains-out.hs
- data/examples/declaration/value/function/infix/dollar-chains.hs
- data/examples/declaration/value/function/infix/lenses-out.hs
- data/examples/declaration/value/function/lambda-multi-line1-out.hs
- data/examples/declaration/value/function/lambda-multi-line2-out.hs
- data/examples/declaration/value/function/let-multi-line-out.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Keep the ($) operator on the same line in certain cases

- data/examples/declaration/data/field-layout/gadt-out.hs
- data/examples/declaration/data/field-layout/gadt.hs
- data/examples/declaration/data/field-layout/record-out.hs
- data/examples/declaration/data/field-layout/record.hs
- data/examples/declaration/data/field-layout/variants-out.hs
- data/examples/declaration/data/field-layout/variants.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
> More precise layouts in precise of Haddocks in data definitions

- data/examples/declaration/value/function/infix/hanging-out.hs
- data/examples/declaration/value/function/overindentation-out.hs
- data/examples/declaration/value/function/overindentation.hs
- src/Ormolu/Parser/CommentStream.hs
- src/Ormolu/Printer/Internal.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Fix the “overindentation” issues with function applications

- data/examples/declaration/foreign/foreign-export-out.hs
- src/Ormolu/Printer/Meat/Declaration/Foreign.hs
> Fix a minor inconsistency between normal and foreign type signatures

- CHANGELOG.md
- data/examples/module-header/preceding-comment-with-haddock-out.hs
- data/examples/module-header/preceding-comment-with-haddock.hs
- src/Ormolu/Printer/Meat/Module.hs
> Fix moving comments before module header into the export list

- CHANGELOG.md
- data/examples/other/empty-forall-out.hs
- data/examples/other/empty-forall.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
- src/Ormolu/Printer/Meat/Declaration/Rule.hs
- src/Ormolu/Printer/Meat/Type.hs
> Preserve empty ‘forall’s

- CHANGELOG.md
- data/examples/module-header/stack-header-0-out.hs
- data/examples/module-header/stack-header-0.hs
- data/examples/module-header/stack-header-1-out.hs
- data/examples/module-header/stack-header-1.hs
- data/examples/module-header/stack-header-2-out.hs
- data/examples/module-header/stack-header-2.hs
- src/Ormolu/Parser.hs
- src/Ormolu/Parser/CommentStream.hs
- src/Ormolu/Printer/Comments.hs
- src/Ormolu/Printer/Meat/Module.hs
> Handle stack header correctly

- data/examples/declaration/value/function/block-arguments-out.hs
- data/examples/declaration/value/function/block-arguments.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> remove do-block braces in arguments

- CHANGELOG.md
- data/examples/declaration/value/function/multi-way-if-out.hs
- data/examples/declaration/value/function/multi-way-if.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Fix application of multi-way if to arguments

- CHANGELOG.md
- data/examples/declaration/value/function/type-applications-out.hs
- data/examples/declaration/value/function/type-applications.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Fix indentation in presence of type applications

- data/examples/declaration/value/function/record-dot-out.hs
- data/examples/declaration/value/function/record-dot.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Differentiate recordDot & standard record updates

- ormolu.cabal
- tests/Ormolu/PrinterSpec.hs
This is needed by hie(https://github.com/haskell/haskell-ide-engine/pull/1482)
> Bump version bounds

- CHANGELOG.md
- app/Main.hs
> Don't give up on first failure when multiple files are given

- CHANGELOG.md
- data/examples/declaration/value/function/pattern/famous-cardano-pattern-out.hs
- data/examples/declaration/value/function/pattern/multiline-case-pattern-out.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Make rendering of operator patterns consistent with other cases

- CHANGELOG.md
- data/examples/declaration/type-families/closed-type-family/multi-line-out.hs
- src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs
> More compact rendering of type family injectivity constraints

- CHANGELOG.md
- data/examples/declaration/class/dependency-super-classes-out.hs
- data/examples/declaration/class/functional-dependencies-out.hs
- data/examples/declaration/class/multi-parameters2-out.hs
- data/examples/declaration/data/gadt/multiline-where-out.hs
- data/examples/declaration/data/gadt/multiline-where.hs
- data/examples/declaration/type-families/closed-type-family/multi-line-out.hs
- src/Ormolu/Printer/Meat/Declaration/Class.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
- src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs
> Improve rendering of "where" in class declarations and such

- CHANGELOG.md
- app/Main.hs
- data/examples/declaration/data/field-layout/record-out.hs
- data/examples/declaration/data/record-multi-const-out.hs
- data/examples/declaration/data/record-multi-const.hs
- data/examples/declaration/data/record-out.hs
- data/examples/declaration/data/simple-broken-out.hs
- data/examples/declaration/instance/data-family-instances-newtype-out.hs
- src/Ormolu/Config.hs
- src/Ormolu/Parser/Result.hs
- src/Ormolu/Printer/Internal.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
> Format records with a single data constructor more compactly

- .buildkite/pipeline.yml
- default.nix
- nix/nixpkgs/default.nix
- src/Ormolu/Parser/Pragma.hs
- src/Ormolu/Printer/Meat/Declaration.hs
- src/Ormolu/Printer/Operators.hs
> Run the build with 3 latest GHC versions

- CHANGELOG.md
- data/examples/declaration/value/function/do/blocks-out.hs
- data/examples/declaration/value/function/do/comment-alignment-out.hs
- data/examples/declaration/value/function/do/comment-alignment.hs
- data/examples/declaration/value/function/do/comment-spacing-out.hs
- data/examples/declaration/value/function/do/comment-spacing.hs
- data/examples/declaration/value/function/do/recursive-do-rec-out.hs
- expected-failures/Agda.txt
- expected-failures/brick.txt
- expected-failures/idris.txt
- expected-failures/intero.txt
- expected-failures/leksah.txt
- expected-failures/pandoc.txt
- src/Ormolu/Printer/Combinators.hs
- src/Ormolu/Printer/Comments.hs
- src/Ormolu/Printer/Internal.hs
- src/Ormolu/Printer/Meat/Common.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #74, close #536. This is an experiment to find an alternative to #536.
> Preserve grouping of do statements

- data/examples/declaration/splice/grouped-splices-out.hs
- data/examples/declaration/splice/grouped-splices.hs
- data/examples/declaration/splice/splice-decl.hs
- data/examples/declaration/value/function/let-single-line-out.hs
- src/Ormolu/Printer/Meat/Declaration.hs
- src/Ormolu/Utils.hs
> Preserve grouping of TH splices

- data/examples/other/cpp/continuation-out.hs
- data/examples/other/cpp/continuation.hs
> Add a CPP macro continuation test

- CHANGELOG.md
- app/Main.hs
- default.nix
- region-tests/expected-result-5-6.hs
- region-tests/expected-result-5-7.hs
- region-tests/expected-result-8-12.hs
- region-tests/expected-result-all.hs
- region-tests/src.hs
- src/Ormolu.hs
- src/Ormolu/Config.hs
- src/Ormolu/Parser.hs
- src/Ormolu/Parser/Result.hs
- src/Ormolu/Printer.hs
- src/Ormolu/Processing/Preprocess.hs
- src/Ormolu/Utils.hs
> Allow selection of a region to format

- CHANGELOG.md
- app/Main.hs
- data/examples/module-header/double-dot-with-names-out.hs
- data/examples/module-header/multiline2.hs
- data/examples/module-header/preceding-comment-with-haddock-out.hs
- data/examples/module-header/singleline-empty-out.hs
- data/examples/module-header/warning-pragma-multiline-out.hs
- data/examples/module-header/warning-pragma-out.hs
- data/examples/other/pragma-comments-out.hs
- data/examples/other/pragma-out.hs
- default.nix
- expected-failures/Agda.txt
- expected-failures/idris.txt
- expected-failures/pandoc.txt
- region-tests/expected-result-6-7.hs
- region-tests/expected-result-6-8.hs
- region-tests/expected-result-9-13.hs
- region-tests/expected-result-all.hs
- region-tests/src.hs
- src/Ormolu/Printer/Meat/Declaration/Warning.hs
- src/Ormolu/Printer/Meat/Module.hs
- tests/Ormolu/PrinterSpec.hs
> Fix rendering of module headers

- src/GHC.hs
- src/Ormolu/Diff.hs
- src/Ormolu/Parser.hs
- src/Ormolu/Parser/Result.hs
- src/Ormolu/Printer/Combinators.hs
- src/Ormolu/Printer/Comments.hs
- src/Ormolu/Printer/Meat/Module.hs
- src/Ormolu/Utils.hs
Module span is dummy and misleading. Right now it is not used at all, but we
still organize code as if it were used.
> Factor out the 'isModule' function and the use of module span

- CHANGELOG.md
- data/examples/declaration/value/function/operator-comments-2-out.hs
- data/examples/declaration/value/function/operator-comments-2.hs
- src/Ormolu/Printer/Internal.hs
> Fix the difference in indentation levels in a comment series

- CHANGELOG.md
- data/examples/declaration/data/gadt/multiline-out.hs
- data/examples/declaration/data/multiline-arg-parens-out.hs
- data/examples/declaration/data/with-weird-haddock-out.hs
- data/examples/declaration/data/with-weird-haddock.hs
- data/examples/declaration/type-synonyms/with-weird-haddock-out.hs
- data/examples/declaration/type-synonyms/with-weird-haddock.hs
- data/examples/declaration/value/function/arrow/proc-do-complex-out.hs
- data/examples/declaration/value/function/multi-way-if-out.hs
- data/examples/declaration/value/function/operator-comments-2-out.hs
- data/examples/other/comment-two-blocks-out.hs
- expected-failures/Agda.txt
- expected-failures/idris.txt
- src/Ormolu/Printer/Internal.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
- src/Ormolu/Printer/Meat/Declaration/Type.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Fixed an idempotence issue in type synonym declarations

- CHANGELOG.md
- data/examples/declaration/value/function/if-with-comment-out.hs
- data/examples/declaration/value/function/if-with-comment.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Improve rendering of comments around if expressions

- CHANGELOG.md
- data/examples/declaration/data/unnamed-field-comment-0-out.hs
- data/examples/declaration/data/unnamed-field-comment-0.hs
- data/examples/declaration/data/unnamed-field-comment-1-out.hs
- data/examples/declaration/data/unnamed-field-comment-1.hs
- expected-failures/Agda.txt
- src/Ormolu/Printer/Meat/Common.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
- src/Ormolu/Printer/Meat/Type.hs
> Fix rendering of unnamed fields of data constructors

- CHANGELOG.md
- data/examples/declaration/data/partly-documented-out.hs
- data/examples/declaration/data/partly-documented.hs
- expected-failures/idris.txt
- src/Ormolu/Printer/Meat/Declaration/Data.hs
> Fix non-idempotent transformation of partly documented data definition

- CHANGELOG.md
- data/examples/other/disabling/indented-fragment-out.hs
- data/examples/other/disabling/indented-fragment.hs
- src/Ormolu/Parser/CommentStream.hs
- src/Ormolu/Processing/Common.hs
- src/Ormolu/Processing/Postprocess.hs
- src/Ormolu/Processing/Preprocess.hs
> Handle magic comments for disabling/enabling with more flexibility

- CHANGELOG.md
- data/examples/other/comment-trailing-space-out.hs
- data/examples/other/comment-trailing-space.hs
- src/Ormolu/Printer/Internal.hs
> Avoid outputting trailing whitespace in multiline comments

- CHANGELOG.md
- data/examples/declaration/value/function/type-applications-and-splice-out.hs
- data/examples/declaration/value/function/type-applications-and-splice.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Prevent type applications from gluing to TH splices that follow them

- ormolu.cabal
Resolves https://github.com/tweag/ormolu/issues/596
> Fix build errors with nix on macOS

- CHANGELOG.md
- default.nix
- region-tests/expected-result-17-18.hs
- region-tests/expected-result-6-8.hs
- region-tests/expected-result-9-12.hs
- region-tests/expected-result-all.hs
- region-tests/src.hs
- src/Ormolu/Parser.hs
- src/Ormolu/Parser/Result.hs
- src/Ormolu/Printer.hs
- src/Ormolu/Processing/Postprocess.hs
- src/Ormolu/Utils.hs
Close #572.
Improved region formatting so that indented fragments can also be processed correctly.
> Deal with non-zero indentation in region formatting

- CHANGELOG.md
- data/examples/import/deduplication-bug-out.hs
- data/examples/import/deduplication-bug.hs
- src/Ormolu/Imports.hs
> Fixed the bug in the de-duplicating algorithm for import lists

- CHANGELOG.md
- data/examples/other/pragma-comments-after-out.hs
- data/examples/other/pragma-comments-after.hs
- src/Ormolu/Parser/CommentStream.hs
> Fix the bug related to de-association of pragma comments

- CHANGELOG.md
- data/examples/import/merging-0-out.hs
- data/examples/import/merging-0.hs
- data/examples/import/merging-1-out.hs
- data/examples/import/merging-1.hs
- data/examples/import/merging-2-out.hs
- data/examples/import/merging-2.hs
- data/examples/import/qualified-post-out.hs
- data/examples/import/qualified-prelude-out.hs
- data/examples/import/simple-out.hs
- expected-failures/leksah.txt
- src/Ormolu/Diff.hs
- src/Ormolu/Imports.hs
- src/Ormolu/Printer/Meat/Module.hs
- src/Ormolu/Processing/Preprocess.hs
- src/Ormolu/Utils.hs
> Implement merging on imports

- CHANGELOG.md
- data/examples/other/comment-glued-together-out.hs
- data/examples/other/comment-glued-together.hs
- expected-failures/idris.txt
- src/Ormolu/Printer/Comments.hs
> Fix the bug when comments in different styles get glued together

- CHANGELOG.md
- app/Main.hs
> Add ‘-i’ as a shortcut for ‘--mode inplace’

- CHANGELOG.md
- data/examples/declaration/signature/type/infix-promoted-type-constructor-out.hs
- data/examples/declaration/signature/type/unrelated-out.hs
- data/examples/declaration/signature/type/unrelated.hs
- data/examples/declaration/value/function/implicit-params-out.hs
- data/examples/declaration/value/function/implicit-params.hs
- data/examples/other/argument-comment-out.hs
- data/examples/other/cpp/separation-2b-out.hs
- expected-failures/Agda.txt
- expected-failures/intero.txt
- src/Ormolu/Printer/Meat/Declaration.hs
- src/Ormolu/Printer/Meat/Declaration.hs-boot
- src/Ormolu/Printer/Meat/Declaration/Value.hs-boot
> Improve grouping of top-level type signatures

- README.md
> readme: fix typo of "accommodate"

- CHANGELOG.md
- data/examples/declaration/type/promotion-out.hs
- data/examples/declaration/type/promotion.hs
- src/Ormolu/Printer/Meat/Type.hs
> Guarantee a space before ticked promoted types

- CHANGELOG.md
- data/examples/declaration/value/pattern-synonyms/bidirectional.hs
- data/examples/declaration/value/pattern-synonyms/explicitely-bidirectional-out.hs
- data/examples/declaration/value/pattern-synonyms/explicitely-bidirectional.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Make single-line explicit bidirectional pattern synonyms idempotent

- ormolu.cabal
Builds fine and all tests pass here.
> Allow path 0.8

- CHANGELOG.md
- data/examples/declaration/value/function/comprehension/transform-monad-out.hs
- data/examples/declaration/value/function/comprehension/transform-monad.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
Fixes #665.
I tested this with just the new example files, and it failed. Adding the change to Value.hs made it succeed.
> Support MonadComprehensions.

- data/examples/declaration/signature/standalone-kind-out.hs
- data/examples/declaration/signature/standalone-kind.hs
- src/Ormolu/Printer/Meat/Declaration.hs
> group StandaloneKindSignatures with type synonyms

- CHANGELOG.md
- data/examples/declaration/value/function/arrow/proc-applications2-out.hs
- data/examples/declaration/value/function/arrow/proc-applications2.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
I took a stab at implementing a fix to #716.
- this seems to work, but comes mostly from mental pattern matching, not understanding
- the examples are based on GHC test suite test cases; should they be simplified and/or should the origin be documented?
- not sure about naming of the example file (or whether the example should go in one of the existing files)
> Implement HsCmdApp (fixes #716)

- CHANGELOG.md
- data/diff-tests/inputs/no-trailing-blank-line.hs
- data/diff-tests/inputs/with-trailing-blank-line.hs
- data/diff-tests/outputs/no-preceding.txt
- data/diff-tests/outputs/simple-hunk.txt
- data/diff-tests/outputs/trailing-blank-line.txt
- src/Ormolu/Diff/Text.hs
- tests/Ormolu/Diff/TextSpec.hs
> Detect missing trailing blank lines with `--mode check`

- ormolu.cabal
> Modernize cabal files

- CHANGELOG.md
- data/examples/declaration/data/gadt/multiline-where-out.hs
- data/examples/declaration/data/gadt/multiline-where.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
> Format data declarations with multiline kind signatures correctly

- CHANGELOG.md
- data/examples/declaration/value/function/arrow/proc-forms2-out.hs
- data/examples/declaration/value/function/arrow/proc-forms2.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Format infix command formations like usual operators

- CHANGELOG.md
- data/examples/declaration/value/function/block-arguments-out.hs
- data/examples/declaration/value/function/block-arguments.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Omit braces on repeated application of `do` blocks

- CHANGELOG.md
> Mention new intentional formatting failures

- .gitignore
- README.md
- stack.yaml
> Add stack.yaml

- CHANGELOG.md
- data/examples/declaration/splice/quasiquote-out.hs
- data/examples/declaration/splice/quasiquote.hs
- data/examples/other/cpp/continuation-out.hs
- data/examples/other/cpp/continuation.hs
- data/examples/other/cpp/lonely-hash-out.hs
- data/examples/other/cpp/lonely-hash.hs
- data/examples/other/cpp/separation-0a-out.hs
- data/examples/other/cpp/separation-0a.hs
- data/examples/other/cpp/separation-0b-out.hs
- data/examples/other/cpp/separation-0b.hs
- data/examples/other/cpp/separation-1a-out.hs
- data/examples/other/cpp/separation-1a.hs
- data/examples/other/cpp/separation-1b-out.hs
- data/examples/other/cpp/separation-1b.hs
- data/examples/other/cpp/separation-2a-out.hs
- data/examples/other/cpp/separation-2a.hs
- data/examples/other/cpp/separation-2b-out.hs
- data/examples/other/cpp/separation-2b.hs
- data/examples/other/cpp/shifted-out.hs
- data/examples/other/cpp/shifted.hs
- data/examples/other/cpp/simple-import-out.hs
- data/examples/other/cpp/simple-import.hs
- src/Ormolu/Parser.hs
- src/Ormolu/Processing/Preprocess.hs
> Only handle CPP if CPP is actually enabled

- CHANGELOG.md
- data/examples/declaration/value/function/operators-7-out.hs
- data/examples/declaration/value/function/operators-7.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Preserve braces in the left hand side of `:`

- CHANGELOG.md
- data/examples/declaration/value/function/multiple-guards.hs
- data/examples/declaration/value/function/pattern/many-guards-in-singleline-out.hs
- data/examples/declaration/value/function/pattern/many-guards-in-singleline.hs
- data/examples/declaration/value/function/pattern/multiline-guard-statement-out.hs
- data/examples/declaration/value/function/pattern/multiline-guard-statement.hs
- data/examples/declaration/value/function/pattern/multiple-guard-statements-out.hs
- data/examples/declaration/value/function/pattern/multiple-guard-statements.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #712.
I don't think this solution is acceptable, but it's still a starting
point to see that it can be made if we really want it.
> Fix multiline pattern bind indent (#712)

- CHANGELOG.md
- data/examples/declaration/rewrite-rule/never-active-out.hs
- data/examples/declaration/rewrite-rule/never-active.hs
- src/Ormolu/Printer/Meat/Declaration/Signature.hs
> Preserve rewrite rules that are never active

- CHANGELOG.md
- data/examples/declaration/value/pattern-synonyms/explicitely-bidirectional-out.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Format bidirectional pattern synonyms nicer

- README.md
Ref: https://github.com/tweag/ormolu/issues/710#issuecomment-864436964
> Add reference to the trailing comma problem and fourmolu

- CHANGELOG.md
- data/examples/other/disabling/suffix-comment-out.hs
- data/examples/other/disabling/suffix-comment.hs
- src/Ormolu/Processing/Preprocess.hs
> Allow non-blank text after magic comments

- .buildkite/pipeline.yml
- cabal.project
- default.nix
- extract-hackage-info/extract-hackage-info.cabal
- nix/sources.json
- ormolu.cabal
> Maintenance: update versions of some dependencies

- default.nix
- nix/pkgs.nix
- nix/sources.json
Closes #859 
Test run: https://github.com/amesgen/ormolu/actions/runs/1847329055
> Bump nixpkgs via haskell.nix for macdylibbundler 1.0.4

- README.md
The old link is seemingly broken.
> Update the IOHK Hydra setup instructions

- CHANGELOG.md
- data/diff-tests/inputs/applicative-after.hs
- data/diff-tests/inputs/applicative-before.hs
- data/diff-tests/inputs/longer-v2.hs
- data/diff-tests/inputs/longer.hs
- data/diff-tests/outputs/no-preceding.txt
- data/diff-tests/outputs/simple-hunk.txt
- data/diff-tests/outputs/trimming-trailing-both-eof.txt
- data/diff-tests/outputs/trimming-trailing-both-out-of-margin.txt
- src/Ormolu/Diff/Text.hs
- tests/Ormolu/Diff/TextSpec.hs
> Fix some bugs in the diff printing code

- CHANGELOG.md
- data/examples/declaration/value/function/list-comprehensions-out.hs
- data/examples/declaration/value/function/list-comprehensions.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
> Indent closing bracket for list comprehensions in `do` blocks

- CHANGELOG.md
- data/examples/declaration/type-families/closed-type-family/with-comments-out.hs
- data/examples/declaration/type-families/closed-type-family/with-comments.hs
- src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs
> Indent comments in closed type familiy declarations

- CHANGELOG.md
- data/examples/declaration/value/function/operator-fixity-defaulting-out.hs
- data/examples/declaration/value/function/operator-fixity-defaulting.hs
- expected-failures/pandoc.txt
- src/Ormolu/Fixity/Internal.hs
- src/Ormolu/Printer/Meat/Declaration/OpTree.hs-boot
- tests/Ormolu/HackageInfoSpec.hs
- tests/Ormolu/OpTreeSpec.hs
> Default fixity to infixl 9

- .github/workflows/ci.yml
https://github.com/tweag/ormolu/pull/984#pullrequestreview-1274337547
> Add Stack CI to keep `stack.yaml` up-to-date

- CHANGELOG.md
- data/examples/declaration/data/unnamed-field-comment-0-out.hs
- data/examples/declaration/data/unnamed-field-comment-1-out.hs
- data/examples/declaration/data/unnamed-field-comment-2-out.hs
- data/examples/declaration/data/unnamed-field-comment-2.hs
- data/examples/declaration/data/unnamed-field-comment-3-out.hs
- data/examples/declaration/data/unnamed-field-comment-3.hs
- src/Ormolu/Fixity/Internal.hs
- src/Ormolu/Printer/Meat/Declaration/Data.hs
- src/Ormolu/Printer/Meat/Type.hs
> Format haddocks attached to arguments of data constructors with pipe

- CHANGELOG.md
- data/examples/declaration/type-families/closed-type-family/promotion-out.hs
- data/examples/declaration/type-families/closed-type-family/promotion.hs
- data/examples/declaration/type/promotion-1-out.hs
- data/examples/declaration/type/promotion-1.hs
- src/Ormolu/Printer/Meat/Type.hs
> Insert space before char literals in ticked promoted constructs

- CHANGELOG.md
- data/examples/declaration/value/function/application-1-out.hs
- data/examples/declaration/value/function/application-2-out.hs
- data/examples/declaration/value/function/arrow/proc-applications2-out.hs
- data/examples/declaration/value/function/arrow/proc-do-simple1-out.hs
- data/examples/declaration/value/function/arrow/proc-do-simple1.hs
- data/examples/declaration/value/function/arrow/proc-form-do-indent-out.hs
- data/examples/declaration/value/function/multi-way-if-out.hs
- src/Ormolu/Fixity.hs
- src/Ormolu/Printer/Combinators.hs
- src/Ormolu/Printer/Internal.hs
- src/Ormolu/Printer/Meat/Declaration/OpTree.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs-boot
- src/Ormolu/Printer/Operators.hs
Closes #1002, using the approach of https://github.com/tweag/ormolu/issues/1002#issuecomment-1502291081
It turns out that this also makes it easy to fix #730, see `HsCmdApp`.
> Improve consistency when formatting certain applicands

- CHANGELOG.md
- data/examples/declaration/data/datatype-contexts-out.hs
- data/examples/declaration/data/datatype-contexts.hs
- expected-failures/brittany.txt
- src/Ormolu/Printer/Meat/Declaration/Data.hs
> Support `DatatypeContexts`

- CHANGELOG.md
- README.md
- app/Main.hs
- fixity-tests/default.nix
- src/Ormolu.hs
- src/Ormolu/Utils/Cabal.hs
- src/Ormolu/Utils/Fixity.hs
- src/Ormolu/Utils/IO.hs
> Locate .ormolu file independently of .cabal files

- CHANGELOG.md
- data/examples/import/sorted-package-imports-out.hs
- data/examples/import/sorted-package-imports.hs
- src/Ormolu/Imports.hs
> Put `"this"` `PackageImports` at the end

- CHANGELOG.md
- README.md
> Two minor doc tweaks

- Setup.hs
It is trivial and makes no difference.
> Remove Setup.hs

- extract-hackage-info/extract-hackage-info.cabal
- ormolu.cabal
Inspired by https://github.com/mrkkrp/megaparsec/pull/548, which see.
> Correct dependency bounds

- ormolu-live/cbits/init.c
This PR does even more aggressive cleanup of wasm module before snapshotting, let's see if it helps in further shrinking the wasm module size :)
> Improve ormolu live wasm size

- README.md
> Document parsability requirement for region formatting

- data/examples/declaration/value/function/list-comprehensions-out.hs
- data/examples/declaration/value/function/list-comprehensions.hs
- src/Ormolu/Printer/Meat/Declaration/Value.hs
This chunk of code was a bit hard to digest, so rewritten to be easier to understand. Broken out from #1119
> Refactor gatherStmt

- CHANGELOG.md
- src/Ormolu/Fixity/Parser.hs
- tests/Ormolu/Fixity/ParserSpec.hs
> Fixity parser: don't require trailing newline

- src/Ormolu/Processing/Preprocess.hs
Trivial PR, see the commit description
> `!!?` array indexing operator: fix typo

- .github/workflows/binaries.yml
- .github/workflows/ci.yml
- cabal.project
Test run for the the binaries CI: https://github.com/amesgen/ormolu/actions/runs/12928308291
> Various CI tweaks
