tweag/ormolu

data/examples/declaration/value/function/static-pointers-out.hs, data/examples/declaration/value/function/static-pointers.hs, data/examples/declaration/value/function/type-applications-out.hs, data/examples/declaration/value/function/type-applications.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Hey,
I tried to use ormolu on one my projects, and saw a few unimplemented constructs and decided to implement it.
These are pretty small changes, since StaticPointers is like an ordinary function application and TypeApplications is like an ordinary parameter.
I do not know if you prefer separate PR's for these two, but the change is small enough that a single PR can be easily reviewed/merged.
---
Also a quick question, I want to try implementing a few more constructs, however they are more complex. I believe I can still come up with working implementations, but they will be less than ideal and you will need to go through them again. Would you prefer that, or do you prefer you or someone else to implement them from scratch?
=> Implement TypeApplications and StaticPointers support

data/examples/declaration/value/function/guards-out.hs, data/examples/declaration/value/function/if-multi-line-out.hs, data/examples/declaration/value/function/let-multi-line-out.hs, src/Ormolu/Printer/Meat/Declaration/Pat.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
This formatting scheme is more appropriate if you think of chaining multiple infix expressions and combining it with do-blocks. The operator should hang on previous line instead going first on the next line, e.g.:
```
foo +
bar
```
instead of
```
foo
+ bar
```
=> Change formatting of operators and infix constructors

data/examples/declaration/value/function/do-out.hs, data/examples/declaration/value/function/do.hs, data/examples/declaration/value/function/lambda-case-out.hs, data/examples/declaration/value/function/lambda-multi-line-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
I hacked something together until we can parse `do` notation.
It currently doesn't look pretty because I couldn't find a way to put the `do` keyword in the same line as the previous line; since, as far as I understand, `ormolu` thinks everything should be multi-lined since the whole construct spans multiple lines. I'd appreciate if you can point me to a solution.
=> Initial support for do notation

data/examples/declaration/value/function/case-multi-line-out.hs, data/examples/declaration/value/function/do-out.hs, data/examples/declaration/value/function/do.hs, src/Ormolu/Printer/Meat/Declaration/Pat.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
The change is obvious from the examples.
=> Handle “prefixed blocks” when they go after an operator

data/examples/declaration/instance/associated-data-out.hs, data/examples/declaration/instance/associated-data.hs, data/examples/declaration/instance/associated-types-out.hs, data/examples/declaration/instance/associated-types.hs, data/examples/declaration/instance/contexts-out.hs, data/examples/declaration/instance/contexts.hs, data/examples/declaration/instance/data-family-instances-out.hs, data/examples/declaration/instance/data-family-instances.hs, data/examples/declaration/instance/empty-instance-out.hs, data/examples/declaration/instance/empty-instance.hs, data/examples/declaration/instance/instance-sigs-out.hs, data/examples/declaration/instance/instance-sigs.hs, data/examples/declaration/instance/multi-parameter-out.hs, data/examples/declaration/instance/multi-parameter.hs, data/examples/declaration/instance/overlappable-instances-out.hs, data/examples/declaration/instance/overlappable-instances.hs, data/examples/declaration/instance/single-parameter-out.hs, data/examples/declaration/instance/single-parameter.hs, data/examples/declaration/instance/type-family-instances-out.hs, data/examples/declaration/instance/type-family-instances.hs, ormolu.cabal, src/Ormolu/Diff.hs, src/Ormolu/Printer/Meat/Common.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Instance.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs, src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs
This pull request implements half of #49. Specifically, it deals with pretty printing instance declarations and most structures needed to support that. This includes pretty printing of associated types (and therefore also type family instances.) However, this _does not_ include pretty printing of associated data types.
Pretty printing of type class declarations is to be dealt with at a later time.
Instances are formatted such that indentation hangs after the `instance`. Namely,
```haskell
instance Eq a
=> Eq [a] where
```
To support pretty printing associated types, the function `p_tyFamInstEqn` was exported from the appropriate module. This was done to avoid redundant code duplication.
As for supporting pretty printing of associated data types: there is a potential (but unimplemented) …
=> Implement rendering of instance declarations

data/examples/declaration/signature/specialize/specialize-out.hs, data/examples/declaration/signature/specialize/specialize.hs, src/Ormolu/Printer/Meat/Module.hs
We should not insert newlines between them.
=> Output multiple specialize pragmas in a row nicer

data/examples/other/argument-comment-out.hs, data/examples/other/argument-comment.hs, src/Ormolu/Printer/Comments.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Type.hs
Close #80.
I'm not sure it's perfect, but it fixes the original issue and all the tests pass.
The problem was in entering with locate (or some version of it) the same span twice. So the algorithm saw an element with identical enclosing element and the `commentFollowsElt` function got confused.
The solution is two first augment registration of enclosing spans to allow us to keep more than one item there. Then we can filter out spans which are just copies of current reference span to get to the “real” enclosing span.
It seems to make sense to attach comments to child element if it starts exactly at the same position of parent element, hence the distance between start of enclosing/reference span and start of comment is the same, thus changing `>` to `>=` in `commentFollowsElt`.
=> Fix Haddock placement for function arguments

data/examples/declaration/signature/type/multi-value-out.hs, data/examples/declaration/signature/type/multi-value.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs
Close #87.
Maybe the style is debatable, but I don't know a better way to format it in multi-line.
=> Fix type signature declarations for multiple values

src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Give a user the chance to see what AST is not supported.
=> Expand all constructor that are missing (no Show instance)

data/examples/declaration/signature/pattern/multiline-out.hs, data/examples/declaration/signature/pattern/multiline.hs, data/examples/declaration/signature/pattern/single-line-out.hs, data/examples/declaration/signature/pattern/single-line.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs
This is a simple addition, adding `pattern ` in front of normal type signature
formatting
=> [#70] Format Pattern Synonym Signatures

data/examples/declaration/class/associated-data-out.hs, data/examples/declaration/class/associated-data.hs, data/examples/declaration/class/associated-type-defaults-out.hs, data/examples/declaration/class/associated-type-defaults.hs, data/examples/declaration/class/associated-types-out.hs, data/examples/declaration/class/associated-types.hs, data/examples/declaration/class/default-implementations-out.hs, data/examples/declaration/class/default-implementations.hs, data/examples/declaration/class/default-signatures-out.hs, data/examples/declaration/class/default-signatures.hs, data/examples/declaration/class/dependency-super-classes-out.hs, data/examples/declaration/class/dependency-super-classes.hs, data/examples/declaration/class/empty-classes-out.hs, data/examples/declaration/class/empty-classes.hs, data/examples/declaration/class/functional-dependencies-out.hs, data/examples/declaration/class/functional-dependencies.hs, data/examples/declaration/class/multi-parameters-out.hs, data/examples/declaration/class/multi-parameters.hs, data/examples/declaration/class/poly-kinded-classes-out.hs, data/examples/declaration/class/poly-kinded-classes.hs, data/examples/declaration/class/single-parameters-out.hs, data/examples/declaration/class/single-parameters.hs, data/examples/declaration/class/super-classes-out.hs, data/examples/declaration/class/super-classes.hs, ormolu.cabal, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Class.hs, src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs, src/Ormolu/Printer/Meat/Type.hs
This pull request implements the latter half of #49. Specifically, it deals with pretty printing type class declarations. This includes pretty printing the associated type and data families.
Like #72, type class declarations are formatted such that indentation hangs after the `class`:
```haskell
class ( Ord a
, Show a
)
=> Foo a where
```
Functional dependencies over multiple lines use a style that is debatable. Specifically,
```haskell
class Bar a b
| a -> b
, b -> a where
```
Obviously feel free to request a change of style if desired.
The only other thing of note aside from that is this: I ended up duplicating the the `tyVarsToTypes` helper function. Alternatively, I could move it and export it from either the `Ormolu.Printer.Meat.Common` or `Ormolu.Printer.Meat.Type` modules.
=> Implement rendering of type class declarations

data/examples/declaration/deriving/multiline-out.hs, data/examples/declaration/deriving/multiline.hs, data/examples/declaration/deriving/singleline-out.hs, data/examples/declaration/deriving/singleline.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Instance.hs
Hi, I hope you don't mind if I take a stab at this.     
I opened the PR just to check if I'm going in the right direction, there's a few things still missing:    
- still need to figure out when is `XDerivDecl` matched
- there might be a refactoring opportunity for the deriving strategy cases (e.g. in [Data.hs:140-165](https://github.com/tweag/ormolu/blob/fab9f15ad6e34165a57b0151de3503710b82898a/src/Ormolu/Printer/Meat/Declaration/Data.hs#L140-L165)) although I don't think all strategies are available \ compatible for standalone deriving (right?)
- it looks like `located (hsib_body (hswc_body deriv_type)) p_hsType` is too crude here since it's not parsing the `via` between the types and thus not triggering a newline
=> [#50] Standalone Deriving

data/examples/declaration/value/function/do-where-out.hs, data/examples/declaration/value/function/do-where.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
The issue here was that `placeHanging` removed the `inci` that would normally be applied to the whole function body and the local bindings. This PR adds an `inci` around the local bindings, conditional on being in `Hanging` mode.
Closes #98
=> [#98] Fix where blocks with do notation

data/examples/declaration/class/associated-data-out.hs, data/examples/declaration/class/associated-data.hs, data/examples/declaration/class/associated-types-out.hs, data/examples/declaration/class/associated-types.hs, data/examples/declaration/class/multi-parameters-out.hs, data/examples/declaration/class/multi-parameters.hs, data/examples/declaration/class/poly-kinded-classes-out.hs, data/examples/declaration/class/poly-kinded-classes.hs, data/examples/declaration/class/type-operators-out.hs, data/examples/declaration/class/type-operators.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Class.hs
This pull request implements certain changes that were accidentally left out of #79. Specifically, it makes the handling of type variables & names for type class pretty printing reuse `p_infixDefHelper` to support infix operator names & parameters over multiple lines. In addition, minor cleanups and refactorings were left out of #79.
=> Support infix operator & multi-line class names

app/Main.hs, src/Ormolu/Exception.hs
This PR adds explicit error codes for different type of errors:
- `0`: Success (no error), as usual
- `1`: `error`/`notImplemented`
- `2`: `OrmoluCppEnabled`
- `3`: `OrmoluParsingFailed`
- `4`: `OrmoluOutputParsingFailed`
- `5`: `OrmoluASTDiffers`
- `100`: `--mode check` input different to output
The motivation for this is to be able to easily know more or less what went wrong from a shell script.
A use case where these error codes would be useful (I intend on making full use of this) would be to use `ormolu --mode check` in a linting suite but to disregard errors in case a given module uses CPP.
=> Use error codes

data/examples/declaration/class/default-implementations-out.hs, data/examples/declaration/class/default-signatures-out.hs, data/examples/declaration/instance/instance-sigs-out.hs, data/examples/declaration/value/function/if-single-line-out.hs, data/examples/declaration/value/function/newline-single-line-body-out.hs, data/examples/declaration/value/function/newline-single-line-body.hs, data/examples/declaration/value/pattern-synonyms/bidirectional-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
The PR changes the body layouting to use a span that includes the last point in
the name/pattern part of a match. This forces the layout to be multiline iff the
body starts on a newline.
Closes #94
=> [#94] Improve handling of newline before match group bodies

data/examples/declaration/splice/bracket-out.hs, data/examples/declaration/splice/bracket.hs, data/examples/declaration/splice/quasiquote-out.hs, data/examples/declaration/splice/quasiquote.hs, data/examples/declaration/splice/splice-decl-out.hs, data/examples/declaration/splice/splice-decl.hs, data/examples/declaration/splice/typed-splice-out.hs, data/examples/declaration/splice/typed-splice.hs, data/examples/declaration/splice/untyped-splice-out.hs, data/examples/declaration/splice/untyped-splice.hs, data/examples/declaration/value/function/pattern/quasi-quotes-pattern-out.hs, data/examples/declaration/value/function/pattern/splice-pattern-out.hs, data/examples/declaration/value/function/quasi-quotes-out.hs, ormolu.cabal, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration.hs-boot, src/Ormolu/Printer/Meat/Declaration/Splice.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Module.hs
This PR does the following:
I haven't been able to format the declaration TH quotes:
```
foo = [d|
bar :: Char
bar = 'c'
|]
```
In order to format the inner `HsDecl`, we need access to `p_hsDecl` from `Declaration.Value`.
I have 2 potential solutions to fix this but I'd like @mrkkrp's point of view before I go ahead and implement one of the two solutions.
1. We inline the `Declaration.Value` module in `Declaration`. I've quickly tried this and it looks like it would basically force us to move all the modules `Declaration.*` into `Declaration` since they basically all use `Declaration.Value` one way or another.
2. We could try to do some _dependency injection_ of the `p_hsDecl` function and pass it as an argument to the functions that need it. I assume this would end up being needed in …
=> Add Splice printer

data/examples/module-header/multiline-empty-out.hs, data/examples/module-header/multiline-empty.hs, src/Ormolu/Printer/Meat/ImportExport.hs
Fixes #114 
- added test case to reproduce the unwanted behavior
- fixed it with an ad-hoc pattern matching in `p_hsmodExports`
=> [#114] removes trailing whitespace from empty export list

data/examples/declaration/value/function/list-comprehensions-out.hs, data/examples/declaration/value/function/list-comprehensions.hs, data/examples/declaration/value/function/parallel-comprehensions-out.hs, data/examples/declaration/value/function/parallel-comprehensions.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
This pull requests implements some parts of list comprehensions as specified in #47. Specifically, it implements normal & parallel list comprehensions. However, it does not implement transform list comprehensions.
There are no real problems to speak of, as the formatting is obvious and consistent with what the Haskell community already does. See the tests for an example.
The reason transform list comprehensions are not implemented yet is because the GHC AST for representing list comprehensions is a horrible mess, where slightly different list comprehensions end up causing massively different syntax trees. The simplest way of solving this would likely be a preprocessing step that reads the syntax trees and produces a simple, linear list of bindings. I decided not to implement this yet to …
=> Implement pretty printing of basic & parallel list comprehensions

.circleci/config.yml, .gitignore, default.nix, nix/gitignore/default.nix, nix/nixpkgs/default.nix, shell.nix
Fixes #64 (tested on my macbook).
- Fixed it by pointing to a newer nixpkgs commit (the commit you pointed to previously is broken on darwin).
- Restructured default.nix and added a shell.nix (now people can use `lorri watch` too if they wish to do so).
- Ran `nixfmt` to give it consistent formatting
All nix commands should stay the same.
=> Cleanup nix config

data/examples/declaration/value/function/lambda-case-out.hs, data/examples/declaration/value/function/lambda-case.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
It was producing invalid output when supplied with a
LambdaCase with a guard.
For example, given input:
```
{-# LANGUAGE LambdaCase #-}
foo = \case
i  | i > 5 -> 11
```
It used to produce (with `--unsafe` flag):
```
{-# LANGUAGE LambdaCase #-}
foo = \case
i -> | i > 5 = 11
```
After this patch:
```
{-# LANGUAGE LambdaCase #-}
foo = \case
i | i > 5 -> 11
```
I couldn't comprehend the entirety of p_match function, 
so it is possible that I am missing something. However
the tests still pass.
=> Correctly print \case's with guards

data/examples/declaration/signature/specialize/specialize-instance-out.hs, data/examples/declaration/signature/specialize/specialize-instance.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs
Part of #70 
- added tests (do I need to cover multiline as well?)
- extended `p_sigDecl'` to handle `SpecInstSig`
=> [#70] implemented specialize instance pragma

data/examples/declaration/data/empty-out.hs, data/examples/declaration/data/empty.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs
Fixes #121 
I hope you don't find it too crude. An alternative would be to move the if-s to a new function with proper pattern matching on the type of declaration. Since these types are not explicit in the GHC AST it might be confusing\overkill. Let me know what you think :)
=> [#121] Support EmptyDataDecls

data/examples/declaration/class/associated-data-out.hs, data/examples/declaration/class/associated-type-defaults-out.hs, data/examples/declaration/class/associated-types-out.hs, data/examples/declaration/class/default-implementations-out.hs, data/examples/declaration/class/default-signatures-out.hs, data/examples/declaration/class/dependency-super-classes-out.hs, data/examples/declaration/class/functional-dependencies-out.hs, data/examples/declaration/class/multi-parameters-out.hs, data/examples/declaration/class/single-parameters-out.hs, data/examples/declaration/signature/minimal/minimal-out.hs, src/Ormolu/Printer/Meat/Common.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration.hs-boot, src/Ormolu/Printer/Meat/Declaration/Class.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Module.hs
This pull request adds newlines between most declarations in a type class, as specified in #110. Certain other kinds of declarations (such as associated type signatures and bindings) are grouped together without newlines. The process for determining which declarations are grouped reuses the same logic as for modules.
Sorting of type class declarations now wraps everything up in a `HsDecl` instead of pre-pretty-printing everything ahead of time. Since the way in which declarations inside of type classes are pretty printed may vary (e.g. type families), a specialized pretty printer called `p_associatedDecl` is partially copied from `p_hsDecl`. This is a minor bit of code duplication. However, since the behavior is relatively different and constrained, I believe this minor code duplication …
=> Add newlines between most declarations in a type class

data/examples/declaration/instance/associated-data-out.hs, data/examples/declaration/instance/associated-types-out.hs, data/examples/declaration/instance/contexts-out.hs, data/examples/declaration/instance/instance-sigs-out.hs, data/examples/declaration/instance/multi-parameter-out.hs, data/examples/declaration/instance/overlappable-instances-out.hs, data/examples/declaration/instance/single-parameter-out.hs, data/examples/declaration/signature/specialize/specialize-instance-out.hs, src/Ormolu/Printer/Meat/Declaration/Instance.hs
This pull request adds newlines between most declarations in a type class instance, completing the changes specified in #110 and #120. Certain other kinds of declarations, such as instance signatures (e.g., from `InstanceSigs`) and bindings, are grouped together without newlines. The process for determining which declarations are grouped reuses the same logic as for modules and type classes.
Sorting of type class instance declarations now wraps everything up in a `HsDecl` instead of pretty printing everything ahead of time. Once the declarations are wrapped up, the `p_hsDecls` pretty printer is reused for pretty printing and handling newlines between declarations.
Otherwise, a newline is also added before the first declaration, similarly to #120.
=> Add newlines between most declarations in a type class instance

data/examples/declaration/value/function/arrow/expression-applications-out.hs, data/examples/declaration/value/function/arrow/expression-applications.hs, data/examples/declaration/value/function/arrow/expression-forms-out.hs, data/examples/declaration/value/function/arrow/expression-forms.hs, data/examples/declaration/value/function/arrow/proc-applications-out.hs, data/examples/declaration/value/function/arrow/proc-applications.hs, data/examples/declaration/value/function/arrow/proc-cases-out.hs, data/examples/declaration/value/function/arrow/proc-cases.hs, data/examples/declaration/value/function/arrow/proc-do-complex-out.hs, data/examples/declaration/value/function/arrow/proc-do-complex.hs, data/examples/declaration/value/function/arrow/proc-do-simple-out.hs, data/examples/declaration/value/function/arrow/proc-do-simple.hs, data/examples/declaration/value/function/arrow/proc-forms-out.hs, data/examples/declaration/value/function/arrow/proc-forms.hs, data/examples/declaration/value/function/arrow/proc-ifs-out.hs, data/examples/declaration/value/function/arrow/proc-ifs.hs, data/examples/declaration/value/function/arrow/proc-lambdas-out.hs, data/examples/declaration/value/function/arrow/proc-lambdas.hs, data/examples/declaration/value/function/arrow/proc-lets-out.hs, data/examples/declaration/value/function/arrow/proc-lets.hs, data/examples/declaration/value/function/arrow/proc-parentheses-out.hs, data/examples/declaration/value/function/arrow/proc-parentheses.hs, data/examples/declaration/value/function/arrow/recursive-procs-out.hs, data/examples/declaration/value/function/arrow/recursive-procs.hs, data/examples/declaration/value/function/do-out.hs, data/examples/declaration/value/function/do.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
This pull request implements all facets of arrow notation (as far as I know), as specified in #47. Most syntactic constructs reuse pretty printing specified previously, such as arrow cases, if-expressions and lambdas. Relevant operators (such as arrow argument passing) and brackets are also formatted as operators and brackets typically are.
Note that supporting arrow notation necessitates a need to generalise `p_stmt` and `p_matchGroup`, since arrow notation *literally* reuses these syntactic constructs, except so-called "arrow commands" are used instead of expressions. In theory, all these functions could be duplicated and specialised for arrows, though that seems undesirable.
Relevant expressions (e.g. proc notation) will hang properly, in a similar way to case expressions and do …
=> Implement all facets of arrow notation

data/examples/declaration/class/dependency-super-classes-out.hs, data/examples/declaration/class/functional-dependencies-out.hs, data/examples/declaration/class/multi-parameters-out.hs, data/examples/declaration/class/poly-kinded-classes-out.hs, data/examples/declaration/class/super-classes-out.hs, data/examples/declaration/class/type-operators-out.hs, data/examples/declaration/instance/contexts-out.hs, data/examples/declaration/instance/contexts.hs, data/examples/declaration/instance/overlappable-instances-out.hs, data/examples/declaration/instance/overlappable-instances.hs, src/Ormolu/Printer/Meat/Declaration/Class.hs, src/Ormolu/Printer/Meat/Declaration/Instance.hs, src/Ormolu/Printer/Meat/Type.hs
Close #113.
This pull request implements the constraint context formatting specified in #113 and approved by @mrkkrp. Essentially, it simply indents the constraints one layer, instead of hanging the constraints off of `class` or `instance`.
Also, this pull request inadvertently fixes a bug in type pretty printing, where constraint types that do not end in function types cause potentially redundant breakpoints.
=> Implement properly indented constraint contexts

data/examples/declaration/annotation/annotation-out.hs, data/examples/declaration/annotation/annotation.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Annotation.hs
Just like other pragmas annotations will now “stick” to the definitions they pertain to. If it's not possible, there will be a newline separating them from other declarations in the module.
=> Insert newlines after annotations in certain cases

data/examples/other/comment-alignment-out.hs, data/examples/other/comment-alignment.hs, src/Ormolu/Printer/Comments.hs
Fixes #138
This PR adds a check for Haddock comments `-- |` so that they don't count as logically following.
Do you think I should add some checks for multiline comments starting with `{- |` as well?
=> Recognize gaps between comment blocks

data/examples/declaration/instance/single-parameter-out.hs, data/examples/declaration/value/function/arrow/proc-cases-out.hs, data/examples/declaration/value/function/arrow/proc-forms-out.hs, data/examples/declaration/value/function/arrow/proc-lambdas-out.hs, data/examples/declaration/value/function/case-multi-line-out.hs, data/examples/declaration/value/function/do-out.hs, data/examples/declaration/value/function/lambda-single-line-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #94.
Now the printing code can correctly detect when hanging constructions should be placed in non-hanging fashion from the way they are placed in input source code.
=> Improve handling of newlines

src/Ormolu.hs
Without this info it's hard to know which file from a bulk is problematic.
=> Mention name of file even when rendered version fails to parse

app/Main.hs, data/examples/declaration/value/function/list-comprehensions.hs, ormolu.cabal, src/Ormolu/Config.hs, src/Ormolu/Parser.hs
What could be better?
* Fixes #69 (because it drops `yaml` dependency).
* Fixes #62 (because it enabled all extensions).
* Fixes #56 (because messing with cabal files is no longer necessary).
=> Abolish ‘yaml’ configuration

data/examples/declaration/value/function/do-out.hs, data/examples/declaration/value/function/do.hs, data/examples/declaration/value/function/let-multi-line-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #145.
It is a bit uncommon to format it like this, but this way it can be placed without changes in do blocks as well. I think it's the right way go about that bug.
=> Shift ‘in’ in ‘let’ to the right to allow placing it in do blocks

data/examples/declaration/value/pattern-synonyms/bidirectional-out.hs, data/examples/declaration/value/pattern-synonyms/bidirectional.hs, data/examples/declaration/value/pattern-synonyms/explicitely-bidirectional-out.hs, data/examples/declaration/value/pattern-synonyms/explicitely-bidirectional.hs, data/examples/declaration/value/pattern-synonyms/unidirectional-out.hs, data/examples/declaration/value/pattern-synonyms/unidirectional.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Previously we forgot to enable the extension, and apparently we were just defining a function called `pattern`.
=> Fix rendering of implicit bidirectional pattern synonyms

data/examples/declaration/data/kind-annotations-out.hs, data/examples/declaration/data/kind-annotations.hs, data/examples/declaration/value/function/implicit-params-out.hs, data/examples/declaration/value/function/implicit-params.hs, src/Ormolu/Printer/Meat/Type.hs
Previously there was no space between type variable and `::`, which is why I started digging this in the first place.
=> Adjust rendering of kind signatures and implicit parameters

data/examples/declaration/data/multiline-names-out.hs, data/examples/declaration/data/multiline-names.hs, data/examples/declaration/instance/associated-data-out.hs, data/examples/declaration/instance/data-family-instances-out.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Instance.hs
Close #151.
This pull request fixes the bug in #151 where data types with infix names & names layed out over multiple lines get incorrectly formatted. Specifically, this pull request reuses `p_infixDefHelper` to easily take care of this behavior.
No other changes to formatting (such as e.g. indentation) are applied. Consequently, certain cases (such as `GADTs`) may at times look awkward:
```haskell
data
Foo
(a :: Type)
(b :: Type) where
Foo :: a -> b -> Foo a b
Bar :: b -> a -> Foo a b
```
=> Support data types with infix & multi-line declarations

data/examples/declaration/value/function/transform-comprehensions-out.hs, data/examples/declaration/value/function/transform-comprehensions.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
This pull request implements pretty printing of transform list comprehensions, as specified in the `TransStmt` part of #47.
Supporting such comprehensions while also keeping the codebase readable was surprisingly difficult, largely since the GHC AST for list comprehensions is notoriously difficult to work with. The simplest approach to solving the problem was to preprocess all list comprehensions and generate nested lists of statements, where the first layer correspond to parallel statements, and the second layer correspond to sequenced statements. Consequently, pretty printing of list comprehensions becomes a mere nested traversal.
All list comprehension preprocessing happens in `gatherStmt`, `gatherStmtBlock`, and `liftAppend`, which simply extracts the relevant statements into the …
=> Support transform list comprehensions

src/Ormolu.hs, src/Ormolu/Diff.hs, src/Ormolu/Exception.hs
Close #202.
This should help with #200 
Before this patch:
```
$ ormolu -m inplace cmm/CmmBuildInfoTables.hs
AST of input and AST of formatted code differ.
Please, consider reporting the bug.
```
After this patch:
```
$ ormolu -m inplace cmm/CmmBuildInfoTables.hs
AST of input and AST of formatted code differ.
at cmm/CmmBuildInfoTables.hs:1:1
at cmm/CmmBuildInfoTables.hs:411:13-39
at cmm/CmmBuildInfoTables.hs:419:9-57
Please, consider reporting the bug.
```
=> Include source locations in diff report

data/examples/declaration/value/function/do-out.hs, data/examples/declaration/value/function/do.hs, data/examples/declaration/value/function/let-single-line-out.hs, data/examples/declaration/value/function/let-single-line.hs, data/examples/declaration/value/function/where-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #177
This PR implements the first fix suggested in #177
It adds support for single line `where` clauses which has the effect of fixing the issue with the interaction between `let` and `where` clauses in the single line case.
=> Fix let/where single line

app/Main.hs, src/Ormolu/Parser.hs
See #163
```
$ ormolu -l
BangPatterns
BinaryLiterals
ConstraintKinds
DataKinds
DefaultSignatures
DeriveAnyClass
DerivingStrategies
DerivingVia
EmptyCase
EmptyDataDecls
ExistentialQuantification
ExplicitForAll
ExplicitNamespaces
ExtendedDefaultRules
FlexibleContexts
FlexibleInstances
ForeignFunctionInterface
FunctionalDependencies
GADTs
GADTSyntax
GeneralizedNewtypeDeriving
HexFloatLiterals
ImplicitParams
IncoherentInstances
InstanceSigs
KindSignatures
LambdaCase
MultiParamTypeClasses
MultiWayIf
NPlusKPatterns
NamedWildCards
NegativeLiterals
NumericUnderscores
OverlappingInstances
OverloadedLabels
OverloadedLists
OverloadedStrings
PackageImports
PatternGuards
PolyKinds
QuantifiedConstraints
QuasiQuotes
RankNTypes
RecordPuns
RecordWildCards
RecursiveDo
RoleAnnotations
ScopedTypeVariables …
```
=> Add an option to display default extensions.

README.md, app/Main.hs, default.nix, nix/gitignore/default.nix, nix/ormolize/default.nix, nix/ormolize/ormolize.sh, src/Ormolu.hs, src/Ormolu/Config.hs, src/Ormolu/Diff.hs, src/Ormolu/Exception.hs, src/Ormolu/Parser.hs
=> Run on Hackage

data/examples/declaration/value/pattern-synonyms/bidirectional-out.hs, data/examples/declaration/value/pattern-synonyms/bidirectional.hs, data/examples/declaration/value/pattern-synonyms/unidirectional-out.hs, data/examples/declaration/value/pattern-synonyms/unidirectional.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
This fixes #191 about curly braces being removed when using record pattern synonyms.
=> Fix Record Pattern Synonyms

data/examples/declaration/value/other/comments-get-before-op-out.hs, data/examples/declaration/value/other/comments-get-before-op.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #174.
This puts out the fire, but I'm not fully content with the solution. I also do not understand why it fails in the original issue but succeeds for e.g.:
```haskell
foo = do
1
+
2
```
=> Avoid failing when comments get before an operator

data/examples/declaration/value/function/arrow/proc-do-complex-out.hs, data/examples/declaration/value/function/arrow/proc-forms-out.hs, data/examples/declaration/value/function/arrow/proc-ifs-out.hs, data/examples/declaration/value/function/arrow/proc-lets-out.hs, data/examples/declaration/value/function/case-multi-line-out.hs, data/examples/declaration/value/function/do-out.hs, data/examples/declaration/value/function/do.hs, data/examples/declaration/value/function/guards-out.hs, data/examples/declaration/value/function/if-multi-line-out.hs, data/examples/declaration/value/function/lambda-multi-line-out.hs, data/examples/declaration/value/function/let-multi-line-out.hs, data/examples/declaration/value/function/list-comprehensions-out.hs, data/examples/declaration/value/function/operators-out.hs, data/examples/declaration/value/function/operators.hs, data/examples/declaration/value/function/parallel-comprehensions-out.hs, data/examples/declaration/value/function/pattern/splice-pattern-out.hs, data/examples/declaration/value/function/transform-comprehensions-out.hs, data/examples/declaration/value/other/comments-get-before-op-out.hs, default.nix, src/Ormolu/Printer/Comments.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #95, close #176, close #179 and close #207, close #220.
Currently, all tests are pasing except `declaration/value/function/parallel-comprehensions.hs`, where there is an issue about comment placement which makes the AST differ. The comment issue can be summarized as:
```haskell
-- before
main =
bar $ -- bar
baz -- baz
-- after
main =
bar
$ baz -- baz -- bar
```
Besides the comment issue, I also did not implement the special treatment of `do` notation yet, so currently the common idiom:
```haskell
foo $ do
bar
baz
```
now becomes:
```haskell
foo
$ do
bar
baz
```
Which looks a bit unusual, but syntactically valid. Otherwise all looks reasonable to me. I tested a few major Hackage packages and couldn't find any introduced regressions and on the plus side now we can format `pandoc`.
I …
=> Change formatting of the operators

data/examples/declaration/data/gadt-syntax-out.hs, data/examples/declaration/splice/bracket-out.hs, data/examples/declaration/splice/splice-decl-out.hs, data/examples/declaration/splice/splice-decl.hs, data/examples/declaration/value/function/do-out.hs, data/examples/declaration/value/function/operators-out.hs, data/examples/declaration/warning/warning-multiline-out.hs, data/examples/declaration/warning/warning-single-line-out.hs, data/examples/declaration/warning/warning-single-line.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Annotation.hs, src/Ormolu/Printer/Meat/Declaration/Class.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Default.hs, src/Ormolu/Printer/Meat/Declaration/Foreign.hs, src/Ormolu/Printer/Meat/Declaration/Instance.hs, src/Ormolu/Printer/Meat/Declaration/RoleAnnotation.hs, src/Ormolu/Printer/Meat/Declaration/Rule.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs, src/Ormolu/Printer/Meat/Declaration/Splice.hs, src/Ormolu/Printer/Meat/Declaration/Type.hs, src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Module.hs
Close #196
The actual solution was simply indenting the closing `|]` one more level. However there were a few more issues around them, which led me to a slightly bigger refactor.
The main reason is that, all `p_*Decl` functions used to print a trailing newline. This makes sense for top-level constructs, however it was making printing something like `[d|data Foo = Foo|]` impossible.
In this PR, I removed trailing newlines from individual printers and gave that responsibility to `p_hsDecls`, and inserted an additional trailing newline when printing modules.
While doing that, I noticed a few bugs/inconsistencies, and I had to fix them in the process:
* Warning pragmas used to not print a trailing newline, so they were always attached to the next expression. I made it more like the other …
=> Fix printing of TH brackets

data/examples/declaration/warning/warning-single-line-out.hs, data/examples/declaration/warning/warning-single-line.hs, data/examples/module-header/warning-pragma-multiline-out.hs, data/examples/module-header/warning-pragma-out.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Warning.hs, src/Ormolu/Printer/Meat/Module.hs
Closes #262 .
Just tweak the layout handling on module header a bit, and a minor fix on the part where we decide if we should separate two declarations.
=> Tweak formatting of warning pragmas

data/examples/declaration/splice/quotes-out.hs, data/examples/declaration/splice/quotes.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
closes #275 .
1. Haskell Reports [says that](https://www.haskell.org/onlinereport/haskell2010/haskellch2.html) any unicode symbol or punctuation can be used as operators, so I added `isSymbol` to the `isOperator`. This fixed the issue of not recognising `==` as an operator.
2. I modified `isOperator`'s definition so that it requires all characters to be an operator. This fixed the issue of recognising `foo_bar` as an operator.
=> Fix TH quoting of operators

data/examples/declaration/signature/specialize/specialize-out.hs, data/examples/declaration/signature/specialize/specialize.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs
This PR makes `SPECIALIZE` pragma's render `InlineSpec`'s, like:
```haskell
{-# SPECIALIZE INLINE mapTCMT :: () #-}
```
=> Support inline specs inside specialize pragmas

data/examples/declaration/type/promotion-out.hs, data/examples/declaration/type/promotion.hs, src/Ormolu/Printer/Meat/Type.hs
Closes #285 .
It looks like this issue was partially known at #184, however
a few promoted contructs was missing (lists and tuples).
=> Fix the issue with promoted containers with promoted elements

data/examples/declaration/rewrite-rule/basic-out.hs, data/examples/declaration/rewrite-rule/basic.hs, src/Ormolu/Printer/Meat/Declaration/Rule.hs
Closes #279 .
It looks like rewrite rule names are parsed exactly as string literals. Therefore, `\` is used as escape character, and we have to unescape it when printing.
Instead of manually unescaping it, I just print it as a string literal. Another way would be to just use SourceText, but this one feels nicer to me.
=> Fix printing of the rewrite rule names

data/examples/declaration/annotation/annotation-out.hs, data/examples/declaration/annotation/annotation.hs, src/Ormolu/Printer/Meat/Declaration/Annotation.hs
Close #278.
GHC grammar [says](https://github.com/ghc/ghc/blob/284a2f44666c88616c9f4426e566014f8685669c/compiler/parser/Parser.y#L1776) that we need to use the "type" keyword when attaching annotations to types.
=> Correctly format when adding annotations to types

data/examples/declaration/value/function/operators-out.hs, data/examples/declaration/value/function/operators.hs, src/Ormolu/Printer/Comments.hs
Closes #294 .
It looks like changing the relative position of the closing brace can cause whitespace changes.
=> Print multiline comments without changing the contents

data/examples/declaration/value/function/let-multi-line-out.hs, data/examples/declaration/value/function/let-multi-line.hs, data/examples/declaration/value/function/let-single-line-out.hs, data/examples/declaration/value/function/let-single-line.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes: #276 .
This PR implements implicit parameter bindings. eg.
```
let ?a = b
in  foo
```
This PR is based on #271, so we should wait until that is merged. You can look at the [last commit](https://github.com/tweag/ormolu/pull/293/commits/0592786527e0f4c25cf0252048a0402776cef258) to see the changes.
=> Implement implicit parameter bindings

data/examples/declaration/value/function/record-constructors-out.hs, data/examples/declaration/value/function/record-constructors.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #280 #281 .
This PR places the expressions on record constructor fields using 'placeHanging'.
=> Hang record constructor fields

data/examples/declaration/rewrite-rule/prelude-out.hs, data/examples/declaration/value/other/comments-get-before-op-out.hs, data/examples/other/comment-inside-construct-out.hs, data/examples/other/comment-inside-construct.hs, src/Ormolu/Printer/Comments.hs
Closes #295 .
In this PR, I try to attach the comment if the next element is not a sibling. I think this is quite often what we want, since if we put a comment inside a construct, we prefer it to stay inside the same element.
=> Try to contain comments inside enclosing contructs

data/examples/declaration/class/type-operators-out.hs, data/examples/declaration/class/type-operators.hs, data/examples/declaration/data/multiline-names-out.hs, data/examples/declaration/value/function/infix-out.hs, src/Ormolu/Printer/Meat/Common.hs, src/Ormolu/Printer/Meat/Type.hs
Closes #259 .
This changes the type-level infix operators on infix operators on pattern matches use the new style (newline after the operator instead of before).
This slightly makes the Servant-like signatures a bit more bearable, and makes the type-level and value-level code look more alike (example from #171):
```haskell
type API
= "sso" :> APISSO
:<|> "sso-initiate-bind"
:> APIAuthReq
:<|> "identity-providers"
:> APIIDP
:<|> "scim"
:> APIScim
:<|> OmitDocs
:> "i"
:> APIINTERNAL
-- value level equivalent
api =
"sso" :> APISSO
:<|> "sso-initiate-bind"
:> APIAuthReq
:<|> "identity-providers"
:> APIIDP
:<|> "scim"
:> APIScim
:<|> OmitDocs
:> "i"
:> APIINTERNAL
```
=> Use new operator style in types & declarations

data/examples/declaration/value/function/parallel-comprehensions-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #301.
This pull request removes indentation of the '|' character in parallel list comprehensions by one layer, as specified in #301. Said indentation was caused by a use of `sitcc` which, when removed, aligns things properly.
A comment is also added to document this in case anyone later wonders why one expression uses `sitcc` and the other does not.
=> Dedent parallel list comprehensions by one step

data/examples/declaration/value/function/block-arguments-out.hs, data/examples/declaration/value/function/block-arguments.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #241 .
When the value of the function application has a hanging form (can happen after `-XBlockArguments`), hang the construct.
=> Hang after block arguments

ormolu.cabal
One nice thing is that beginning from Cabal 2.4 we can use ** wildcard in paths, which is especially useful in our case because we have many examples in a big directory tree, so without ** listing all the directories correctly is a real pain.
All other changes are just to satisfy Cabal's nitpicks.
=> Update cabal file

data/examples/declaration/splice/bracket-out.hs, data/examples/declaration/splice/splice-decl-out.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Comments.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Common.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Module.hs
Close #203 .
Both `[e|...|]` and `[||]` mean the same thing, and instead of sticking to a single style, we can just preserve what user wrote.
=> Preserve the name of the expression bracket

app/Main.hs, nix/ormolize/ormolize.sh, src/Ormolu.hs, src/Ormolu/Config.hs, src/Ormolu/Diff.hs, src/Ormolu/Exception.hs
Closes #274 .
This PR adds a new command line flag called "--check-idempotency" which formats the output again and checks if the output is exactly the same as the first pass.
In order to get nicer error messages, I also added a simple support for showing where the errors differ on the error messages. Here is an example error message:
```
Formatting is not idempotent:
test/Tests/Writers/RST.hs<rendered>:106:13
before: "       =: -- pandoc "
after:  "       =: strong (sp"
Please, consider reporting the bug.
```
I checked a few packages and it looks like most of the issues are about newlines or comment placement.
=> Implement --check-idempotency flag

data/examples/declaration/value/function/block-arguments-out.hs, data/examples/declaration/value/function/case-multi-line-out.hs, data/examples/declaration/value/function/do-out.hs, data/examples/declaration/value/function/if-multi-line-out.hs, data/examples/declaration/value/function/lambda-multi-line-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #299.
This arguably improves readability especially when if-then-else is placed inside of a `do`-block.
Argumentation for choosing this style is that I like it more than the alternatives.
=> Indent ‘then’ and ‘else’ clauses one level further

data/examples/declaration/value/function/if-multi-line-out.hs, data/examples/declaration/value/function/if-multi-line.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #316.
This PR hangs expressions in if-then-else expressions. eg.
```
if gen == gen0 && newlen <= cap0
then do
let newgen = gen + 1
marr <- unsafeThaw arr0
writeGen marr newgen
A.copyI marr (off0 + len0) arr1 off1 (off0 + newlen)
arr2 <- A.unsafeFreeze marr
return (Buf arr2 off0 newlen cap0 newgen)
else do
let newcap = newlen * 2
newgen = 1
marr <- A.new (newcap + woff)
writeGen marr newgen
A.copyI marr woff arr0 off0 (woff + len0)
A.copyI marr (woff + len0) arr1 off1 (woff + newlen)
arr2 <- A.unsafeFreeze marr
return (Buf arr2 woff newlen newcap newgen)
```
=> Hang expressions in if-then-else

data/examples/declaration/instance/associated-data-out.hs, data/examples/declaration/instance/contexts-comments-out.hs, data/examples/declaration/instance/contexts-out.hs, data/examples/declaration/instance/instance-sigs-out.hs, data/examples/declaration/instance/overlappable-instances-out.hs, data/examples/declaration/type/misc-kind-signatures-out.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration.hs-boot, src/Ormolu/Printer/Meat/Declaration/Instance.hs
Closes #170 .
This implements @mrkkrp's suggestion on the ticket of only adding a trailing newline after the instance header when there are multiple declarations.
=> Conditionally add an extra newline on instances

data/examples/declaration/value/function/case-multi-line-guards-out.hs, data/examples/declaration/value/function/case-multi-line-guards.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
closes #328.
Previously 'getGRHSSpan' function was only looking at the span of the body of the pattern ignoring the guard. This was causing an idempotence issue described in #328.
This PR makes 'getGRHSSpan' function merge the span of the body with spans of the guards.
=> Fix an issue with detecting spans of patterns with guards

data/examples/declaration/class/default-implementations-out.hs, data/examples/declaration/class/functional-dependencies-out.hs, data/examples/declaration/class/multi-parameters1-out.hs, data/examples/declaration/class/single-parameters-out.hs, src/Ormolu/Printer/Meat/Declaration/Class.hs
Closes #329.
The same as #170, but for type class definitions.
=> Make the first newline optional on class declarations

data/examples/declaration/value/function/where-nested-out.hs, data/examples/declaration/value/function/where-nested.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
This fixes an issue where braces are inserted unnecessarily on some cases like:
```
foo = bar
where
f1 = f1
where
{ f1 = 3 }
f2 = f2
where
f2 = 3
```
=> Only force braces on hsLocalBinds on a single-line layout

data/examples/declaration/signature/type/multi-value-out.hs, data/examples/declaration/signature/type/multi-value.hs, data/examples/declaration/value/function/case-single-line-out.hs, data/examples/declaration/value/function/pattern/n-plus-k-pattern-out.hs, data/examples/declaration/value/function/pattern/n-plus-k-pattern.hs, data/examples/declaration/warning/warning-multiline-out.hs, data/examples/declaration/warning/warning-single-line-out.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration.hs-boot, src/Ormolu/Printer/Meat/Declaration/Class.hs, src/Ormolu/Printer/Meat/Declaration/Instance.hs
Closes #104.
This PR extends the declaration grouping logic to handle declarations referring to multiple names. eg:
```haskell
fst, snd :: Bool
(fst, snd) = (True, False)
fst, snd :: Bool
fst = True
snd = False
```
It makes the logic a bit more complex since now we can not decide whether to separate two declarations solely by themselves. This new method tries to separate given declarations to groups of relevant declarations; and then prints the groups together. It simply:
1. Takes the first declaration and calls it a group "header"
2. Keeps adding the next declaration to the group if it is relevant to either to the group header or to the previous element.
The relevancy logic(previously `separatedDecls`, now `groupedDecls`) is pretty much the same, but now it handles declarations binding …
=> Group declarations referring to multiple names

data/examples/declaration/rewrite-rule/prelude4-out.hs, src/Ormolu/Printer/Comments.hs
Closes #295.
Previously, `lastInEnclosing` predicate did not correctly handling the case where the comment is the last element in the module.
This PR changes the cases to handle the case where `mnSpn == Nothing`.
=> Correctly place comments inside enclosing expressions at the end of the module

data/examples/declaration/signature/pattern/multiline-out.hs, data/examples/declaration/signature/pattern/multiline.hs, data/examples/declaration/signature/pattern/single-line-out.hs, data/examples/declaration/signature/pattern/single-line.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs
Closes #335.
This PR adds a newline after `pattern` keyword in pattern synonyms
when there are multiple names. eg.
```
pattern
TypeSignature,
FunctionBody,
PatternSignature,
WarningPragma
:: [RdrName]
-> HsDecl GhcPs
```
It only adds the newline when there are multiple names, because I think this:
```
pattern Arrow
:: Type
-> Type
-> Type
```
looks better than:
```
pattern
Arrow
:: Type
-> Type
-> Type
```
I would be happy to change it if you disagree.
=> Make multi-line multi-name patterns prettier

.circleci/config.yml, README.md, default.nix, nix/nixpkgs/default.nix, ormolu.cabal
As the first release is approaching, we better switch to the ~~latest~~ GHC 8.6.5.
=> Use GHC 8.6.5

data/examples/declaration/value/function/lambda-case-out.hs, data/examples/declaration/value/function/lambda-case.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #347.
Always using a newline causes idempotence issues where previously single-line constructs formatted as multi-line on subsequent runs.
=> Don't use newlines on LambdaCases on single-line layouts

data/examples/declaration/value/function/pattern/as-pattern-out.hs, data/examples/declaration/value/function/pattern/as-pattern.hs, src/Ormolu/Parser.hs
Closes #348.
Turns out TypeApplications interferes with as-patterns in some cases, eg:
```haskell
main = case [1] of
xs @ (x:_) -> print (x, xs)
```
=> Remove TypeApplications from default extensions

data/examples/declaration/value/function/pattern/view-pattern-out.hs, data/examples/declaration/value/function/pattern/view-pattern.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #343.
This makes some syntactically incorrect programs not fail on Ormolu. The formatted code will still cause syntax errors.
See [my comment on #343](https://github.com/tweag/ormolu/issues/343#issuecomment-526401738) for details.
I'm happy to fix this issue in some other way if you are not happy with this.
=> Workaround for pattern constructs in expressions

data/examples/declaration/signature/type/unicode-out.hs, data/examples/declaration/signature/type/unicode.hs, data/examples/declaration/value/function/infix/unicode-out.hs, data/examples/declaration/value/function/infix/unicode.hs, src/Ormolu/Parser.hs
Without `-XUnicodeSyntax`, this is a working Haskell program:
```
main = print ('a' → 'a')
where
(→) = (,)
```
However with `-XUnicodeSyntax`, `→` is interpreted as function arrrow (`->`) and it causes a parse error.
Therefore, this PR removes `UnicodeSyntax` from default extensions since it makes Ormolu fail on valid Haskell programs.
We can successfully format `fay` with this PR.
=> Remove UnicodeSyntax from default extensions

.circleci/config.yml, default.nix, nix/ormolize/default.nix
closes #303 .
This PR introduces a `hackageTests` attribute, which, when evaluated runs `ormolize` on a few hand-picked Haskell packages and fails on errors.
While doing that, I also:
* Added a `doCheck` parameter to `ormolize` which causes the build to fail in case of issues.
* Passed `--keep-going` parameter to `nix-build` on CI, so that the first failed build won't immediately stop every other one (the whole command will still fail).
* Commented out some packages with known issues, so we can uncomment them once we fix the issues.
=> Automatically test some Hackage packages on CI

data/examples/declaration/data/kind-annotations-out.hs, data/examples/declaration/data/kind-annotations.hs, src/Ormolu/Printer/Meat/Type.hs
Closes #354.
We were putting a space before type variables if they contain the symbol `'`, but I think it is only necessary if the type is promoted.
I couldn't think of a case where this breaks; tests seem to pass, including `hackageTests`.
=> Remove extra space before type variables with apostrophe

data/examples/declaration/value/pattern-synonyms/bidirectional-out.hs, data/examples/declaration/value/pattern-synonyms/bidirectional.hs, data/examples/declaration/value/pattern-synonyms/explicitely-bidirectional-out.hs, data/examples/declaration/value/pattern-synonyms/explicitely-bidirectional.hs, data/examples/declaration/value/pattern-synonyms/unidirectional-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #355.
This PR adds support for of infix pattern synonyms:
```haskell
pattern a :< b
<- (c, d)
where
a :< b = (c, d)
```
While doing that, I had to refactor the pattern synonym printer; and while doing that changed the layout a bit.
Previously, we were putting the equals sign (`=` or `<-`) right after the lhs. This is quite different than how we format other stuff, where we put the equals sign on the next line. After this PR, we apply the same logic to pattern synonyms where the arrow starts on the next line. Here is the difference:
```haskell
-- previously
pattern Tup a =
( a,
a
)
-- now
pattern Tup a
= ( a,
a
)
-- type synonyms
type Tup a
= ( a,
a
)
```
Let me know if you're happy with the change of the formatting.
=> Support infix pattern synonyms

data/examples/other/comment-following-preceding-gap-out.hs, data/examples/other/comment-following-preceding-gap.hs, default.nix, src/Ormolu/Printer/Internal.hs
I noticed that `tls` fails the idempotence check, even though the example I extracted is terribly similar to the problem I just fixed in #356.
=> Enable checking the ‘tls’ package on CI

data/examples/declaration/value/function/lambda-single-line-out.hs, data/examples/declaration/value/function/lambda-single-line.hs, data/examples/declaration/value/function/pattern/strictness-out.hs, data/examples/declaration/value/function/pattern/strictness.hs, src/Ormolu/Parser.hs
Here is an example which fails to parse with bang patterns but succeeds otherwise:
```haskell
(!) :: Foo -> Int -> Int
(Foo n) ! p = n + p
```
To run Ormolu on this we must not enable bang patterns by default.
=> Do not enable -XBangPatterns by default

data/examples/declaration/type-synonyms/multi-line-out.hs, data/examples/declaration/value/function/infix/lenses-out.hs, data/examples/declaration/value/function/infix/lenses.hs, data/examples/declaration/value/function/list-comprehensions-out.hs, default.nix, ormolu.cabal, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Type.hs, src/Ormolu/Printer/Operators.hs
Close #315.
This PR is just a WIP to work on operator precedence handling.
It currently contains a function to apply known fixities to a tree of operators. For now, I am using hard-coded list of fixities borrowed from HSE and HLint's codebases. In the final version of this PR, we are supposed to have a way to automatically infer fixities from the code layout. Alternatively, we can use a mix of approaches where we use hard-coded precedences for Prelude functions and try to infer the ones coming from external libraries.
It introduces a data structure called `OpTree`, which represents a tree of expressions and operators. The reason for the data structure is to be able to handle expressions and types in the same way. The alternative is to accept the AST alongisde with a bunch of accessors; …
=> Operator fixity handling

data/examples/declaration/signature/inline/inline-out.hs, data/examples/declaration/signature/inline/inline.hs, src/Ormolu/Printer/Meat/Declaration.hs
Closes #371.
This PR removes the newline after type signatures if the next declaration is a relevant pragma:
```
+reVector :: Bundle u a -> Bundle v a
+{-# INLINE reVector #-}
+reVector = M.reVector
```
=> Group together pragmas after type signatures

data/examples/declaration/type/lits-out.hs, data/examples/declaration/type/lits.hs, data/examples/declaration/value/function/strings-out.hs, data/examples/declaration/value/function/strings.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs-boot, src/Ormolu/Printer/Meat/Type.hs
Closes #369.
Haskell strings can have "gaps", where any amount of whitespace between
two backslashes are ignored. This allows writing multi-line strings. As
an example, all strings below are the same:
```
"foobar"
"foo\   \bar"
"foo\
\bar"
```
When parsing a string literal, lexer usually produces two fields, one
of them is the actual string user wrote as a 'SourceText', the other one
is the sanitized version where gaps and other special characters removed.
While printing the string, GHC's Outputable instance uses the 'SourceText'
field, however since that text contains gaps as-is, we can not change
the original indentation. In order to fix this, this commit splits the
strings by the gaps and print each line separately applying the layout
rules.
Also, it applies the same logic to …
=> Handle string gaps

data/examples/declaration/value/function/case-multi-line-guards-out.hs, data/examples/declaration/value/function/case-multi-line-guards.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Previously guarded expressions were always printed in non-hanging fashion even if they had a hanging form. This change fixes this behavior.
=> Hang guarded equations

data/examples/declaration/value/function/record-constructors-out.hs, data/examples/declaration/value/function/record-constructors.hs, data/examples/declaration/value/function/record-updaters-out.hs, data/examples/declaration/value/function/record-updaters.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #383.
This PR puts parenthesis arounds operators when used as record accessors.
=> Handle operators as record fields

src/Ormolu/Parser.hs
Close #380.
`defaultErrorHandler` makes the exceptions get wrapped as GHC panic's, which is misleading.
It doesn't look like `defaultErrorHandler` is doing a lot other than running `FlushOut`, wrapping exceptions and handling exit codes; so in our case I think just running `FlushOut` should be enough.
GHC sources for details: https://gitlab.haskell.org/ghc/ghc/blob/993804bf40dea77c36f50ff772d112ec69c8a222/compiler/main/GHC.hs#L391
=> Do not use GHC's defaultErrorHandler

data/examples/declaration/value/function/block-arguments-out.hs, data/examples/declaration/value/function/record-constructors-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #381.
This PR makes a few changes on HsApp printer mainly to play well with `-XBlockArguments`.
1. Only hang the last argument.
This is to fix #381. If we hang any other argument, there is a chance that the next argument will be fused to it.
2. Use braces on `HsApp` arguments.
Otherwise:
```haskell
foo = foo bar do { bar } baz
```
causes the AST to differ.
3. Only use the hanging placement when the LHS is one line:
Otherwise it looks strange:
```haskell
foo =
f
bar
baz do
foo
```
4. Hang the construct when the rightmost argument is hanging
This is to allow:
```haskell
foo = foo bar do
baz
```
5. Do not sit when we're using hanging placement
Otherwise we get:
```haskell
func = foo bar do
baz
```
Which is different compared to how we handle `$`:
```haskell
func = foo bar $ do
baz
``` …
=> Tweak hanging logic on HsApp

data/examples/declaration/rewrite-rule/type-signature-out.hs, data/examples/declaration/signature/type/arguments-out.hs, data/examples/declaration/type/forall-out.hs, data/examples/declaration/type/forall.hs, data/examples/declaration/value/function/fancy-forall-0-out.hs, data/examples/declaration/value/function/fancy-forall-0.hs, data/examples/declaration/value/function/fancy-forall-1-out.hs, data/examples/declaration/value/function/fancy-forall-1.hs, src/Ormolu/Printer/Meat/Type.hs
Close #148.
@utdemir I remember you tried to fix this one as well and found it hard to fix properly. I understand that my fix is a bit hacky because of the `txt "   "` bit which I imagine may look very strange in certain situations, but I fail to come up with any such realistic examples. Please take a look at this and tell me what you think.
=> Introduce a breakpoint after ‘forall’ in type signatures

DESIGN.md, README.md
As discussed, we found another design goal. I added it to the readme. Also, keeping `DESIGN.md` in sync with the development is not worth the effort. The formatter now is fully implemented (modulo bugs fixes and keeping it up to date with new GHC versions), so arguably there is no longer need for a
design document.
=> Update the list of goals in the readme

data/examples/declaration/value/function/parens-out.hs, data/examples/declaration/value/function/parens.hs, src/Ormolu/Printer/Meat/Declaration/Type.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Since parens already delimites the construct inside, we can omit braces there.
Saw this issue when formatting Ormolu itself (also on the diff).
=> Don't use braces inside parens

data/examples/declaration/type-families/closed-type-family/with-equal-sign-out.hs, data/examples/declaration/type-families/closed-type-family/with-equal-sign.hs, src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs
Close #420.
Apparently `KindSig` always means double colon, while `TyVarSig` always means equal sign.
=> Fix printing of result type in closed type families

CHANGELOG.md, src/Ormolu.hs, src/Ormolu/Exception.hs, src/Ormolu/Parser.hs
Close #437.
While migrating to `ghc-lib-parser` we accidentally stopped taking into account the `--ghc-opt` options. This commit fixes that and makes sure we do not ignore unrecognized GHC options.
=> Restore ‘--ghc-opt’ options again, report unrecognized options

data/examples/declaration/value/function/infix/dollar-chains-out.hs, data/examples/declaration/value/function/infix/dollar-chains.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #446.
When we are putting an operator after an expression (we
do that when special-casing `$`), we have to make sure that
there are braces in LHS.
=> Use braces when placing `$` after an expression

CHANGELOG.md, data/examples/other/comment-after-preceding-haddock-out.hs, data/examples/other/comment-after-preceding-haddock.hs, src/Ormolu/Printer/Comments.hs
Close #440, close #448.
I originally thought it's a good idea to prevent this, but it looks like it
makes things arguably worse in certain cases even though the Haddocks end up
not associated with their declarations (but they are not associated with
them in the input either, so it's OK).
=> Insert comments between declarations and their preceding Haddocks

CHANGELOG.md, data/examples/module-header/shebang-out.hs, data/examples/module-header/shebang-with-pragmas-out.hs, data/examples/module-header/shebang-with-pragmas.hs, data/examples/module-header/shebang.hs, src/Ormolu/Parser.hs, src/Ormolu/Parser/CommentStream.hs, src/Ormolu/Parser/Result.hs, src/Ormolu/Printer.hs, src/Ormolu/Printer/Meat/Module.hs
Close #377.
Also: rename and document some functions we took from `ghc-exact-print`.
=> Implement correct handling of shebangs

CHANGELOG.md, data/examples/declaration/class/type-operators3-out.hs, data/examples/other/pragma-sorting-out.hs, data/examples/other/pragma-sorting.hs, src/Ormolu/Printer/Meat/Pragma.hs
Close #404.
The order in which language pragmas are put in the input sometimes matters.
This is because some language extensions can enable other extensions, yet
the extensions coming later in the list have the ability to change it. So
here we classify all extensions by assigning one of the four groups to them.
Then we only sort inside of the groups.
=> Take non-commutative nature of language pragmas into account

data/examples/declaration/value/function/record-dot-out.hs, data/examples/declaration/value/function/record-dot.hs, src/GHC/DynFlags.hs, src/Ormolu/Parser.hs, src/Ormolu/Parser/Result.hs, src/Ormolu/Printer.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
closes: #486 
I'll add tests, if this is going to get merged.
This supports the two forms of `RecordDotSyntax` that are likely to be upstreamed `expr.lbl` and `(.lbl)`/` .lbl`.
We detect `-fplugin=RecordDotPreprocessor` and `-pgmF=record-dot-preprocessor` in `-o` arguments or pragmas in files and just do the right thing.
=> Support RecordDotSyntax plugin & preprocessor

CHANGELOG.md, data/examples/declaration/value/function/overindentation-out.hs, data/examples/declaration/value/function/record-constructors-out.hs, data/examples/declaration/value/function/record-inter-comments-out.hs, data/examples/declaration/value/function/record-inter-comments.hs, data/examples/declaration/value/function/record-wildcards-out.hs, data/examples/other/comment-before-hanging-out.hs, data/examples/other/comment-before-hanging.hs, src/GHC/DynFlags.hs, src/Ormolu/Config.hs, src/Ormolu/Parser.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #447.
Previously we hanged record constructors but not record updates. It looks
like unlike other hanging constructions (lambdas, case expressions, and
do-blocks), record constructors and updates should rather be placed
normally. Indeed, when we stop hanging them, many constructions start to
look more reasonable and predictable (see the updated test cases).
Yet the change is not enough to fix the problem in general case: it is
enough to replace the record with a e.g. do-block to get the same failure.
To correct that we adjust what should fit in one line for hanging placement
to fire: now we consider the span between beginning of function and the
start of potentially-hanging construction.
=> Do not hang record constructors

README.md
ormolu has been integrated in [neoformat](https://github.com/sbdchd/neoformat) 3 months ago and it simply works: call `:Neoformat` to format the current buffer in place using `ormolu`.
=> Mention a second vim integration: neoformat

data/examples/declaration/signature/standalone-kind-out.hs, data/examples/declaration/signature/standalone-kind.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs
Closes #530.
This PR implements supports for standalone kind signatures. It formats them similarly to type synonyms, and also groups them together with its relevant constructs.
This PR is based on top of #531, so it should be rebased (only the relevant commits, including and after 7130ac3) after that is merged to master.
=> Support StandaloneKindSignatures

data/examples/import/qualified-post-out.hs, data/examples/import/qualified-post.hs, src/Ormolu/Diff.hs, src/Ormolu/Parser.hs, src/Ormolu/Parser/Result.hs, src/Ormolu/Printer.hs, src/Ormolu/Printer/Meat/ImportExport.hs, src/Ormolu/Printer/Meat/Module.hs
Closes #526.
This PR checks if `ImportQualifiedPost` language extension is enabled, and places the "qualified" keyword accordingly.
Since it causes a change on the AST, it also modifies Ormolu's AST diff check to ignore this change.
This PR is based on top of #531, so it should be rebased (only the relevant commits, including and after 8c0655e) after that is merged to master.
=> Place "qualified" after the module name when ImportQualifiedPost is enabled

CHANGELOG.md, data/examples/declaration/data/existential-multiline-out.hs, data/examples/declaration/data/existential-multiline.hs, data/examples/declaration/data/field-layout/gadt-out.hs, data/examples/declaration/data/field-layout/record-out.hs, data/examples/declaration/instance/data-family-instances-gadt-out.hs, data/examples/other/multiline-forall-out.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Type.hs
Close #427.
----
One change is that we now render type applications in the same style as data type definitions and value applications:
```haskell
-- input
f :: forall x y.
D x y x y
-- output before
f ::
forall x y.
D x y x
y
-- output after
f ::
forall x y.
D x y x y
```
Now in general if there is a newline in the sequence of applications the whole thing will be formatted like this:
```haskell
f ::
forall x y.
D
x
y
x
y
```
instead of being split in some awkward place in the middle of the sequence.
----
Another change is that we do not lump together `forall` and data constructor when deciding on layout.
```haskell
-- input
data D = forall x y.
D x y x y
-- output before
data D
= forall x y.
D
x
y
x
y
-- output after
data D
= forall x y.
D x y x y
```
=> Render type applications similar to value applications

src/Ormolu/Utils.hs
Closes #544.
It looks like when we call 'showSDocUnsafe' it uses `unsafeGlobalDynFlags`
which the `settings` field is not initialised (unless someone calls
`setUnsafeGlobalDynFlags`, `initGhcMonad` or `runGhc`) and throws a panic.
I couldn't pinpoint the exact cause, but I suspect probably there was
a change either on Ormolu or ghc-lib-parser which removed a call to one
of the functions above before we print manualExts.
Anyway, we actually don't need to call `showSDocUnsafe` since we already
have a populated `DynFlags`. This commit removes the unsafe call and passes
the `DynFlags` we have to `showSDoc`.
=> Fix GHC panic on showOutputable

expected-failures/aws.txt, expected-failures/distributed-process.txt, expected-failures/esqueleto.txt, expected-failures/fay.txt, expected-failures/idris.txt, expected-failures/lens.txt, expected-failures/pandoc.txt, expected-failures/purescript.txt, src/Ormolu/Exception.hs
Parse errors are typically not Ormolu errors.
=> Improve the error message in case of a parse error

CHANGELOG.md, data/examples/other/pragma-comments-out.hs, data/examples/other/pragma-comments.hs, data/examples/other/pragma-sorting-out.hs, expected-failures/Agda.txt, expected-failures/idris.txt, ormolu.cabal, src/Ormolu/Parser.hs, src/Ormolu/Parser/CommentStream.hs, src/Ormolu/Parser/Result.hs, src/Ormolu/Parser/Shebang.hs, src/Ormolu/Printer.hs, src/Ormolu/Printer/Comments.hs, src/Ormolu/Printer/Meat/Module.hs, src/Ormolu/Printer/Meat/Pragma.hs
=> Preserve comments on language pragmas and similar

CHANGELOG.md, README.md, data/examples/other/disabling/single-definition-out.hs, data/examples/other/disabling/single-definition.hs, data/examples/other/disabling/whole-file-out.hs, data/examples/other/disabling/whole-file.hs, ormolu.cabal, src/Ormolu/Parser.hs, src/Ormolu/Printer.hs, src/Ormolu/Processing/Common.hs, src/Ormolu/Processing/Postprocess.hs, src/Ormolu/Processing/Preprocess.hs
Close #435.
Ormolu can be turned on and off via the special comments:
```haskell
{- ORMOLU_DISABLE -}
```
and
```haskell
{- ORMOLU_ENABLE -}
```
This allows us to disable formatting selectively for code between these
markers or disable it for the entire file. To achieve the latter, just put
`{- ORMOLU_DISABLE -}` at the very top. Note that the source code should
still be parseable even without the “excluded” part. Because of that the
magic comments cannot be placed arbitrary, but should rather enclose
independent top-level definitions.
=> Allow to disable Ormolu with special comments

data/examples/declaration/signature/type/multi-value-out.hs, data/examples/declaration/signature/type/multi-value.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs
Close #566.
Previously an extra space were erroneously inserted if the first identifier
happened to be one character long.
=> Fix rendering of type signatures concerning several identifiers

CHANGELOG.md, data/examples/declaration/value/function/awkward-comment-0-out.hs, data/examples/declaration/value/function/awkward-comment-0.hs, data/examples/declaration/value/function/awkward-comment-1-out.hs, data/examples/declaration/value/function/awkward-comment-1.hs, default.nix, expected-failures/Agda.txt, expected-failures/idris.txt, expected-failures/intero.txt, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Rule.hs, src/Ormolu/Printer/Meat/Declaration/Type.hs, src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #340.
This resolves a class of idempotence issues when the equality sign happens to be inserted between an element and its comment that follows on the same line. I had to special-case equality sign for this, because all alternative approaches (changing comment association logic or trying to find a more general rule) did not work or fixed this issue yet made other things worse.
There is nothing special about the equality sign per se, but it (always?) starts definitions which have their own `Located` wrappers and it is those spans interfere with the logic of comment association (they are detected as AST elements between the “host” element and its comment) on subsequent
passes. This results in non-idempotent formatting.
The solution is OKish in that it fixes 99% of problems that one …
=> Fix the idempotence bug 340

data/examples/other/multiple-blank-line-comment-out.hs, data/examples/other/multiple-blank-line-comment.hs, src/Ormolu/Parser/CommentStream.hs
Close #518.
Comments that have more than one consecutive blank line will be rendered
with just a single blank line due to how our rendering engine works. I think
that the engine work correctly in this case and we want to generally
normalize blank lines. So what should be fixed is just the check. For that
we remove extra consecutive blank lines when we construct `Comment` values.
=> Fix the false positive about AST differences

CHANGELOG.md, data/examples/import/misc-out.hs, data/examples/import/simple-out.hs, data/examples/import/simple.hs, src/Ormolu/Imports.hs
Sanitizes import lists
```haskell
import Data.Text (a, a)
import Data.Text hiding (a, a)
```
to
```haskell
import Data.Text (a)
import Data.Text hiding (a)
```
This seems sensible to me, although `data/examples/import/misc-out.hs` suggests that the original behavior is as intended?
=> Remove duplicate LIE's from import lists

CHANGELOG.md, data/examples/import/explicit-imports-out.hs, data/examples/import/explicit-imports-with-comments-out.hs, data/examples/import/nested-explicit-imports-out.hs, data/examples/import/qualified-prelude-out.hs, data/examples/import/sorted-export-list-out.hs, data/examples/import/sorted-export-list.hs, src/Ormolu/Imports.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #602.
Previously `RdrName`s were sorted by simple comparison of their names. However, in ASCII not all “operator-like” symbols go after alpha-numeric characters. This resulted in this sort of output:
```haskell
import Linear.Vector ((*^), Additive (..), (^*))
```
The new ordering scheme allows us to separate operators and other names:
```haskell
import Linear.Vector (Additive (..), (*^), (^*))
```
=> Put operators after other names

CHANGELOG.md, app/Main.hs
Currently, when running with `--mode=inplace`, Ormolu always overwrites the files, even when nothing has changed, updating the modified timestamp of the file. This encourages Stack to rebuild everything when only one file has changed.
A quick check to see if the file needs rewriting solves this problem.
I would prefer the API allowed me to only read the file once, but as the `--mode=check` logic also reads the file twice, I decided this wasn't the biggest sin for now.
=>  Avoid modifying correctly-formatted files.

.github/workflows/binaries.yml, .github/workflows/build.sh
Closes #543.
This PR will add binaries for Linux, macOS and Windows when a new release (corresponding to a tag) is created. See [here](https://github.com/amesgen/ormolu/releases/tag/test-release) for an example ([workflow run](https://github.com/amesgen/ormolu/actions/runs/239377467)).
On Linux, the excellent [ghc-musl](https://github.com/utdemir/ghc-musl) by @utdemir is used.
GHC 8.10.1 is used due to this bug on Windows on 8.10.2: https://gitlab.haskell.org/ghc/ghc/-/issues/18550
=> add workflow for release binaries

README.md
I found the original paragraph a bit hard to understand, partly because it used the word "should" which is ambiguous in English. It can be interpreted as "really ought to but sometimes doesn't" or "is morally compelled to". "Must" is less ambiguous.
=> Clarify enabling/disabling

CHANGELOG.md, data/examples/declaration/type/promotion-0-out.hs, data/examples/declaration/type/promotion-0.hs, data/examples/declaration/type/promotion-1-out.hs, data/examples/declaration/type/promotion-1.hs, src/Ormolu/Printer/Meat/Type.hs
Close #668.
In certain cases spaces in this position are unnecessary. Here we try to
make the algorithm smarter so that it doesn't always insert spaces.
=> Avoid inserting a redundant space in front of ticked types

.github/workflows/binaries.yml
[`actions/setup-haskell`](https://github.com/actions/setup-haskell) is deprecated, but [`haskell/actions/setup`](https://github.com/haskell/actions/tree/main/setup) is a drop-in replacement.
Also, updating to 8.10.2.
See [here](https://github.com/amesgen/ormolu/actions/runs/418860529) for a run in my fork.
=> update CI for release binaries

data/examples/declaration/value/function/record/dot-multiline-out.hs, data/examples/declaration/value/function/record/dot-multiline.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #701.
This pull request solves the "second half" of the idempotency bug presented in #701, but there is a another bug (the "first half") for which I do not see an obvious solution. Since the other bug is not directly related to this, I've opened a separate Issue where I explain the problem in detail, see #705.
When Ormolu checks if a record update conforms to the RDP syntax (no space **before** the opening brace), it compares the column numbers of the relevant source spans but not the line numbers. This is why a regular record update of the form
```hs
{-# OPTIONS_GHC -fplugin=RecordDotPreprocessor #-}
def 
{ g = 1 
}
``` 
where the start / end columns of the expression `def`  and the field `g` are aligned in a specific way, "tricks" Ormolu into thinking that this is an RDP record …
=> Fix rendering of regular record updates with RDP enabled

src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Type.hs
Before this there was some logic replicated in p_hsType, what this
change does is instead of printing directly it constructs the
appropriate type and spans to pass to p_hsType
=> Simplify p_conDecl GADT rendering by using p_hsType

CHANGELOG.md, data/examples/declaration/data/ctype-out.hs, data/examples/declaration/data/ctype.hs, src/Ormolu/Printer/Meat/Common.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Foreign.hs
Closes #689
This targets the ghc-9.0 branch right now, which will have to change as soon as #722 has been merged.
---
The `dd_cType` field of [`HsDataDefn`](https://hackage.haskell.org/package/ghc-lib-parser-9.0.1.20210324/docs/GHC-Hs-Decls.html#v:dd_cType) had been ignored previously, which means that `CTYPE` pragmas were simply dropped on formatting.
As an aside: The `dd_ctxt` is also ignored, but the corresponding extension ([`DatatypeContexts`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/exts/datatype_contexts.html#extension-DatatypeContexts)) is deprecated, so I don't know if it is even worth to respect it.
=> preserve CTYPE pragmas in data declarations

CHANGELOG.md, data/examples/declaration/type-families/closed-type-family/type-arguments-out.hs, data/examples/declaration/type-families/closed-type-family/type-arguments.hs, data/examples/declaration/type-families/data-family/type-arguments-out.hs, data/examples/declaration/type-families/data-family/type-arguments.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Instance.hs, src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs, src/Ormolu/Printer/Meat/Type.hs, src/Ormolu/Utils.hs
Closes #698
Previously, `LHsTypeArg` was converted to `LHsType` via `typeArgToType`, but this conversion loses information, namely whether something was a "value argument" (in this case the conversion is correct) or a "type argument" (in this case it is an argument of visible type application):
```haskell
type LHsTypeArg p = HsArg (LHsType p) (LHsKind p)
-- Arguments in an expression/type after splitting
data HsArg tm ty
= HsValArg tm   -- Argument is an ordinary expression     (f arg)
| HsTypeArg SrcSpan ty -- Argument is a visible type application (f @ty)
-- SrcSpan is location of the `@`
| HsArgPar SrcSpan -- See Note [HsArgPar]
```
=> support TypeApplications in data/type family instances

CHANGELOG.md, data/examples/declaration/value/function/arrow/proc-forms2-out.hs, data/examples/declaration/value/function/arrow/proc-forms2.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #718
Previously, we inserted a space before the infix operator in all scenarios, which breaks if the first operand is e.g. a `do` block or a case switch. To preserve the existing behavior, we now only insert a space (instead of a breakpoint) if the first argument is parenthesized.
=> fix formatting of infix arrow command formations

CHANGELOG.md, data/examples/declaration/splice/bracket-declaration-out.hs, data/examples/declaration/splice/bracket-declaration.hs, data/examples/declaration/splice/bracket-out.hs, data/examples/declaration/splice/bracket.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #704 
One could probably write a better detection algorithm whether the bracket code has the `*` actually at its end (and not somewhere in the middle), but I am not sure if this is worth it, especially as the `StarIsType` is scheduled to be removed (see [this GHC proposal](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0143-remove-star-kind.rst)) and `-Wstar-is-type` is already part of `-Wall` in GHC 9.0.
=> surround code in brackets with spaces if it contains a `* ~ Type`

CHANGELOG.md, data/examples/declaration/value/function/application-1-out.hs, data/examples/declaration/value/function/application-2-out.hs, data/examples/declaration/value/function/application-2.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #707 
If we choose to merge this as is, I will create a style tracking issue for the 1 space indentation via `inciHalf`.
I *think*  that `do`, `case of` and `\case` are all constructs where we have to indent the argument by less than `indentStep`, but it might turn out that there are more.
=> fix formatting of applied multi line constructs in do blocks

CHANGELOG.md, ormolu.cabal, src/Ormolu/Parser.hs, tests/Ormolu/Parser/OptionsSpec.hs
Closes #651 
The first of the two new tests also passes without this patch, but it ensures that we maintain the ability to disable extensions per file.
=> allow CLI GHC options to be overriden by file local options

CHANGELOG.md, data/examples/declaration/instance/newlines-between-methods-out.hs, data/examples/declaration/value/function/lexical-negation-out.hs, data/examples/declaration/value/function/lexical-negation.hs, data/examples/declaration/value/function/negation-out.hs, data/examples/declaration/value/function/negation.hs, data/examples/declaration/value/function/negative-literals-out.hs, data/examples/declaration/value/function/negative-literals.hs, src/Ormolu/Parser.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #694 
Close #733
Note that CI would fail without the second commit, as the addition of `NegativeLiterals` to `manualExts` triggers #733 in a lot of places.
=> improve handling of negative literals

CHANGELOG.md, data/examples/declaration/value/function/arrow/proc-applications-out.hs, data/examples/declaration/value/function/arrow/proc-applications.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #737
Compare https://hackage.haskell.org/package/ghc-8.10.2/docs/src/GHC.Hs.Expr.html#HsCmdArrApp
=> Support left-to-right arrow application (fixes #737)

CHANGELOG.md, data/examples/declaration/value/function/arrow/proc-form-do-indent-out.hs, data/examples/declaration/value/function/arrow/proc-form-do-indent.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Close #739
This is mostly applying mental pattern matching, seeing how indentation is handled for parentheses in regular do blocks.
This may well miss some other cases that should be `BracketStyle`-aware, but it does fix the two instances I ran across.
=> Indent closing arrow-banana in do block (fixes #739)

CHANGELOG.md, data/examples/declaration/value/function/arrow/proc-do-complex-out.hs, data/examples/declaration/value/function/arrow/proc-do-complex.hs, data/examples/declaration/value/function/arrow/proc-do-simple1-out.hs, data/examples/declaration/value/function/arrow/proc-do-simple2-out.hs, data/examples/declaration/value/function/arrow/proc-do-simple2.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #753 
As we no longer always insert `newline`s after the "do" in `do` commands, we also have to ensure that the left hand side has braces if necessary.
=> format `do` commands like `do` blocks in expression contexts

default.nix
Closes #342 
Adapted from https://github.com/input-output-hk/haskell.nix/issues/1111.
It does not work with cross compilation to Windows. I tried to debug using [githash](https://hackage.haskell.org/package/githash-0.1.6.1/docs/GitHash.html#v:tGitInfoCwdTry) (which allows to display error messages why git info inclusion failed), and it can't find the `git` executable. Right now, Template Haskell + cross compilation is mostly dark magic for me, so I am not sure how to investigate further.
=> Include git info in executable

.github/workflows/binaries.yml
Previously, `ormolu-Windows.zip` would contain symlinks to `/nix/store`. See [new](https://github.com/amesgen/ormolu/releases/tag/test-haskell.nix-5) vs [old](https://github.com/amesgen/ormolu/releases/tag/test-haskell.nix-latest).
=> Release binaries: store targets of symlinks

CHANGELOG.md, data/examples/declaration/value/function/case-empty-out.hs, data/examples/declaration/value/function/case-empty.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #765
We could detect whether `{}` is present in the source file via `AnnOpen`/`AnnClose`, but I think it is actually nice to format empty case expressions with `{}` in all cases.
=> Render empty case expressions with braces

CHANGELOG.md, expected-failures/Agda.txt, expected-failures/esqueleto.txt, expected-failures/graphql-engine.txt, expected-failures/haxl.txt, expected-failures/hlint.txt, expected-failures/idris.txt, expected-failures/intero.txt, expected-failures/pandoc.txt, expected-failures/pipes.txt, expected-failures/postgrest.txt, nix/ormolize/default.nix, ormolu.cabal, src/Ormolu/Utils/Extensions.hs, tests/Ormolu/CabalExtensionsSpec.hs
Closes #781
The new warning output also revealed another bug with empty `hs-source-dirs`.
=> Improve `--cabal-default-extensions`

.github/workflows/binaries.yml, default.nix
I stumbled upon [this blogpost](https://www.joachim-breitner.de/blog/776-Distributing_Haskell_programs_in_a_multi-platform_zip_file), which mentions [macdylibbundler](https://github.com/auriamg/macdylibbundler), which is *exactly* what we are looking for. :tada:
Example run in my fork:
- https://github.com/amesgen/ormolu/actions/runs/1267537364
- https://github.com/amesgen/ormolu/releases/tag/test-macos-6
But this can also be tested in this repo by creating (and then deleting) a temporary (pre-)release.
=> Build self-contained macOS binary

default.nix
Closes #792. See [here](https://input-output-hk.github.io/haskell.nix/reference/modules/) for documentation about these options.
Test run:
https://github.com/amesgen/ormolu/releases/tag/smaller-binaries
https://github.com/amesgen/ormolu/actions/runs/1276056492
Results:
- Linux: 25.9 MB → 20.1 MB
- macOS: 35.6 MB → 25.7 MB
- Windows: 81.5 MB → 54.7 MB
---
Credits for this suggestion go to @ilyakooo0!
=> Minimize binary sizes

CHANGELOG.md, app/Main.hs, src/Ormolu.hs, src/Ormolu/Utils/IO.hs
Closes #634 
+ Removes the `ormoluStdin` function
+ Generalizes the `ormoluFile` function, to work on either a real file path,
or the special string `"<stdin>"`
+ Refactors the `formatOne` function (to avoid repetitions)
**Identified drawbacks**
+ Real file / STDIN switch is made with a comparison to a special string
(`"<stdin>"`)
+ When using the `in-place` mode with STDIN input, the error message is
shown only after that the STDIN content has been read
=> Allow ormolu -m check for STDIN content

README.md, ormolu-live/deploy.sh
Trivial workaround as `--prod` and `--alias` can not be combined.
=> Add commit hash alias for Ormolu Live

nix/pkgs.nix
Fixes Ormolu Live.
This can be reverted when when we upgrade to a nixpkgs pin (via haskell.nix) containing this version.
=> Use newer Closure Compiler

.github/workflows/binaries.yml, nix/pkgs.nix
Closes #804
We use a custom version of macdylibbundler, namely [`ce13cb5`](https://github.com/amesgen/macdylibbundler/commit/ce13cb585ead5237813b85e68fe530f085fc0a9e) (which was the version before the nixpkgs bump via #779) with [`dd677ce`](https://github.com/auriamg/macdylibbundler/commit/dd677cec46b1eb8f096906d71c67572de491e8c2) for macOS 11 compat on top. Some later commit introduces an issue which prevents transitive dylib dependencies from being patched (see [here](https://github.com/amesgen/ormolu/actions/runs/1467718275)). If I had access to a macOS machine, it would be interesting to bisect to find out which exact commit introduces the issue.
Test run: https://github.com/amesgen/ormolu/actions/runs/1469420664 (runs on 10.15, but I also ensured that building on 11 works fine)
=> Use custom macdylibbundler

.buildkite/pipeline.yml, nix/pkgs.nix, nix/sources.json, ormolu-live/deploy.sh
It turns out that closure compiler is not at fault for Ormolu Live not working, so #834 did not matter. Locally, Ormolu Live works perfectly fine, and even disabling closure compiler on CI does not fix the issue, so my best guess is that some dependency got corrupted and cached. This PR simply bumps haskell.nix which includes (probably unrelated) changes of GHCJS which results in all dependencies being rebuilt. With this, the Ormolu Live built on CI now works again: https://8afdf0d5bb5e7d9b24e2811df9c96b94b388cc44--ormolu-live.netlify.app/ (note that this is a version without closure compiler, so it takes ages to load).
Also, I set `-j`/`--max-jobs` to `1` as excessive parallelism is sometimes involved in such issues. It won't matter for usual CI run times as rebuilding all GHCJS …
=> Fix Ormolu Live by rebuilding all GHCJS dependencies by upgrading haskell.nix

extract-hackage-info/extract-hackage-info.cabal, extract-hackage-info/src/Main.hs
This makes the build fail on Windows (noticed via `nix-build -A binaries.Windows`).
=> Remove `unix` dependency

default.nix
As I am now on NixOS, I started to actually use the nix shell. HLS is cached by the IOHK cache, so one does not have to compile HLS to get into the shell.
=> Add haskell-language-server to dev shell

ormolu-live/src/Main.hs, ormolu.cabal, src/Ormolu.hs, src/Ormolu/Fixity.hs, tests/Ormolu/CabalInfoSpec.hs, tests/Ormolu/HackageInfoSpec.hs
We cache the fixity map (depending on the package set). This speeds up scenarios when ormolu formats many files in the same package context, especially when they use non-standard operators (where #847 doesn't help).
Test suite: from 2.0998s to 1.0540s
`nix-build -A hackageTests`: from 2m14,382s to 1m41,690s
Test.hs:
```haskell
1++++++1
```
`ormolu` is 0.4.0.0, `./ormolu-pre` is before this PR and `./ormolu` is with this PR.
Formatting Test.hs once: No change as expected
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `ormolu -e Test.hs ` | 5.8 ± 0.6 | 5.1 | 8.5 | 1.00 |
| `./ormolu-pre Test.hs ` | 72.5 ± 1.6 | 70.3 | 81.5 | 12.56 ± 1.31 |
| `./ormolu Test.hs ` | 72.6 ± 1.0 | 71.1 | 75.2 | 12.57 ± 1.29 |
Formatting Test.hs 10x and 100x: big speedups
| …
=> Cache operator fixity maps

ormolu-live/ormolu-live.cabal, ormolu-live/src/Main.hs
Previously, as soon as there was any operator in the input, it would become horribly slow. With #848, it is only slow for the first time an operator is entered, and fast afterwards. With this PR, we now do this at startup/loading time (which is already so long that an extra 300ms is probably worth the snapiness afterwards).
=> Ormolu Live: Propagate fixity map cache at startup

ormolu.cabal, src/Ormolu/Fixity.hs, src/Ormolu/Fixity/Internal.hs, tests/Ormolu/OpTreeSpec.hs
I think `Internal` makes it more obvious that the module is not part of the
public API (e.g. the data constructor of `LazyFixityMap` should normally
stay hidden).
=> Rename Ormolu.Fixity.Types to Ormolu.Fixity.Internal

default.nix
While working with the Nix module system I learned that one is supposed to use the nixpkgs lib via the `lib` argument rather than via `pkgs.lib`. This remembered me of this workaround I introduced in Ormolu due to an "infinite recursion" error, and it turns out that applying this new knowledge fixes the issue in a clean way.
=> Remove `lib.mkIf` workaround

ormolu-live/www/index.html
Closes #862 
I managed to reproduce the issue in Chrome (some caching stuff apparently prevented me from encountering it earlier) and ensured moving the script tag into the body (such that it is already part of the DOM when the script loads) fixes the issue (which is a best practice for exactly this reason).
=> Move script tag into the body

stack.yaml
The current `stack.yaml` doesn't build because of nightly's prior issues with happy: https://github.com/commercialhaskell/stackage/issues/6294
=> Fix stack.yaml

src/Ormolu/Printer/Meat/Declaration/Value.hs
`sitcc` was removed as part of the `ghc-lib-parser-9.2` upgrade (#779), but it looks like that was erroneous; the only change that needed to happen in `p_larg` was the removal of `located`. This causes problems in `fourmolu` with leading commas (see https://github.com/fourmolu/fourmolu/issues/148#issuecomment-1086988846), and this fixes it. I'm not quite sure how to come up with a failing test case for this in ormolu, but I'm fairly certain that the removal of `sitcc` is incorrect, and may cause other unexpected behaviors.
=> Add back sitcc to ExplicitTuple.p_arg

CHANGELOG.md, expected-failures/Agda.txt, expected-failures/pipes.txt, src/Ormolu.hs, src/Ormolu/Diff/ParseResult.hs, src/Ormolu/Diff/Text.hs, src/Ormolu/Exception.hs, src/Ormolu/Parser.hs, src/Ormolu/Terminal.hs
Close #877.
Print the diff between the original input and the erroneous result that
Ormolu produces. Also mention --unsafe in the error message.
=> Make errors about AST differences print diffs

CHANGELOG.md, data/cabal-tests/Bar.hs, data/cabal-tests/Foo.hs, data/cabal-tests/test.cabal, ormolu.cabal, src/Ormolu/Utils/Cabal.hs, tests/Ormolu/CabalInfoSpec.hs
Closes #909
Also added regression tests for this and the empty/missing `hs-source-dirs` bug I fixed in #783.
=> Cabal file lookup: fix handling of `hs-source-dirs: .`

CHANGELOG.md, src/Ormolu/Utils/Cabal.hs
Closes #897 
I tested this by creating a cabal project with 10000 trivial modules (just `module A42 where`), all listed in the `.cabal` file. Formatting 1000 of those modules takes
- ~100s before this PR
- 8s with this PR
- 150ms with `--no-cabal`
Eventlog profiling yields that the big majority of the remaining 8s is spent in `findCabalFile`, which seems reasonable as it uses `listDirectory` to find a `.cabal` file, and the directory contains 10000 files. We could make it smarter by taking all input files into account at once, but I think this really is an edge case of this particular test setup, so I didn't go ahead with it.
In general, we now use `NOINLINE` `IORef`s for caching in two places -- if it ever turns out to be necessary, we could take the more principled but invasive approach …
=> Cache `.cabal` file parsing and processing

CHANGELOG.md, data/examples/import/sorted-package-imports-out.hs, data/examples/import/sorted-package-imports.hs, src/Ormolu/Imports.hs
This fixes #905 by sorting imports first by package qualifier,
if any are included, and then by module name. Imports without
package qualifiers are always sorted before those with.
=> Sort imports by package qualifier if present (Fixes #905)

ormolu-live/www/index.html
In my last PR (#918) I accidentally mistyped `script` as `scipt` in ormolu-live's `index.html`. This fixes that.
=> Fix typo in ormolu-live html script tag

ormolu-live/src/Main.hs, ormolu-live/www/editor.css
This uses a (mostly) pure-CSS solution (inspired by [this post](https://www.webtips.dev/add-line-numbers-to-html-textarea)) to add line numbers to the text editor in Ormolu Live. It calculates the desired line number count from the input, and then creates an equivalent number of `span` elements. A CSS counter is then incremented for each span, and the content is set to the counter's value.
As part of this I had to stop letting Bulma style the editor, so I took the opportunity to give it a dark background & white text, which I think looks pretty nice. I'm also happy to try and find something closer to the original style if anyone has particularly strong feelings about it. 
I initially looked at bringing in a dependency for this, but every one I found creates its own `textarea` rather than …
=> [Ormolu-Live] Add line numbers to editor (Fixes #908)

CHANGELOG.md, data/examples/declaration/value/function/pragmas-out.hs, data/examples/declaration/value/function/pragmas.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #925 
This fix (re/ab)uses the `s :: BracketStyle` argument to `p_hsExpr'` in order to decide whether we are in a `do` expression: even though this particular case has nothing to do with brackets, it points to the same underlying problem (some stuff has to be indented only in `do` blocks). This could be potentially confusing for future readers of this code, but the diff is really small, so the effect is not huge in any case.
A slightly more principled fix could look like this: Introduce
```haskell
data InDoBlock = InDoBlock | NotInDoBlock
```
and change `p_hsExpr'`'s signature to
```haskell
p_hsExpr' :: InDoBlock -> HsExpr GhcPs -> R ()
```
as well as provide a function `InDoBlock -> BracketStyle`.
=> Fix formatting of `SCC` pragmas in `do` blocks

CHANGELOG.md, data/examples/declaration/data/existential-unicode-out.hs, data/examples/declaration/data/existential-unicode.hs, data/examples/declaration/splice/bracket-unicode-out.hs, data/examples/declaration/splice/bracket-unicode.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Utils.hs
Closes #934, key function is [`unicodeAnn`](https://hackage.haskell.org/package/ghc-9.4.2/docs/GHC-Parser-Annotation.html#v:unicodeAnn).
I also spotted another case w.r.t. existential types where we were previously only matching the non-Unicode variant, see the added test case.
=> Handle `UnicodeSyntax` variants more consistently

CHANGELOG.md, data/examples/declaration/data/gadt/multiline-out.hs, data/examples/declaration/data/gadt/multiple-declaration-out.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs
Is there a particular reason why `p_hsType` was being called on `unLoc quantifiedType` instead of using the `located` combinator? It seems like it was initially implemented when GADT args + result type were separate, so there wasn't a single HsType object representing the entire type to be located, but now that we have `quantifiedType`, it seems better to be consistent between function signatures + GADT constructors.
=> Use located in GADT

ormolu.cabal
Workaround for #941, until this (upstream) bug can be properly investigated/reported/worked around.
Could be published as a revision for 0.5.1.0 to avoid unpleasant surprises as seen e.g. in #944.
=> Disable `fixity-th` on GHC 9.4

CHANGELOG.md, default.nix, ormolu.cabal, src/Ormolu/Fixity.hs
Close #927, close #941.
The flag caused problems on GHC 9.4 and generally was a magnet for bugs. We are going to try to use `file-embed` unconditionally and make parsing more efficient instead.
=> Eliminate the fixity-th cabal flag

ormolu.cabal, src/Ormolu/Fixity/Internal.hs, tests/Ormolu/CabalInfoSpec.hs
Somewhat of a follow-up to #954. As I removed a few packages, I also went ahead and enabled `-Wunused-packages`. Note this has a false positive for `exe:ormolu` as we depend on `ghc-lib-parser` there only for the `VERSION_ghc_lib_parser` macro which GHC can not be aware of.
=> Remove unused `Lift` instances and packages

.gitignore
This seems to be created when direnv uses a nix flake?
=> Gitignore .direnv/

.github/workflows/ci.yml, flake.lock, flake.nix, ormolu-live/cabal.project, ormolu-live/default.nix, ormolu.cabal
- Update haskell.nix
- adds GHC 9.4.4 to CI
- haskell.nix uses a different cache right now (probably temporarily)
- Update ghc-wasm-meta
- Nix 2.13.2 fixed the bug we encountered: https://github.com/NixOS/nix/issues/7644#issuecomment-1404957780
- Fixes an IFD issue for the macOS binary (it tried to build Linux GHCs...); successful test run is here: https://github.com/amesgen/ormolu/actions/runs/4018230397
=> Update flake inputs, add GHC 9.4.4 to CI, minor tweaks 

ormolu.cabal, src/Ormolu/Printer/SpanStream.hs, tests/Ormolu/CabalInfoSpec.hs
I find `Data.Sequence` has a better API than `DList`, and it avoids adding another dependency (given that most projects use `containers` anyway). The two should have roughly the same performance: https://stackoverflow.com/a/37507346/4966649
Will conflict with https://github.com/tweag/ormolu/pull/985, will resolve after PR is merged
=> Replace DList with Seq

ormolu-live/app/Main.hs, ormolu-live/ormolu-live.cabal, src/Ormolu/Diff/Text.hs, src/Ormolu/Exception.hs, src/Ormolu/Terminal.hs, src/Ormolu/Terminal/QualifiedDo.hs, tests/Ormolu/Diff/TextSpec.hs, weeder.dhall
Implement Term as an AST builder + interpreter, so that tests and ormolu-live (and Fourmolu) don't have to use hacky work-arounds to print exceptions.
The monad instance is a bit sus, but no one should really be using `<-` in any `Term` blocks. If someone does, it'll just blow up in tests. We can get rid of the monad weirdness by just writing everything as
```hs
prettyOrmoluException :: OrmoluException -> PrettyText
prettyOrmoluException = \case
OrmoluParsingFailed s e ->
[ WithBold [putOutputable s]
, ...
]
type PrettyText = [PrettyNode]
data PrettyNode
= OutputText Text
| WithColor Color PrettyText
| WithBold PrettyText
hPutPretty :: ColorMode -> Handle -> PrettyText -> IO ()
getPretty :: PrettyText -> Text
```
But the do-notation does look a bit nicer, so I didn't want to rewrite all …
=> Implement Term as pure operation

flake.lock, ormolu-live/app/Main.hs, ormolu-live/build-wasm.sh, ormolu-live/cbits/init.c, ormolu-live/default.nix, ormolu-live/ormolu-live.cabal, ormolu-live/package-lock.json, ormolu-live/package.json, ormolu-live/src/hackage-info.bin, ormolu-live/src/worker.js, ormolu.cabal, src/Ormolu/Fixity.hs, src/Ormolu/Fixity/Internal.hs, tests/Ormolu/CabalInfoSpec.hs
This uses [Wizer](https://github.com/bytecodealliance/wizer) to pre-initialize Ormolu Live WASM (see the section "Using `wizer` to pre-initialize a WASI reactor module" in the [ghc-wasm-meta README](https://gitlab.haskell.org/ghc/ghc-wasm-meta/)), including the parsing of the fixity DB.
This indeed improves the time it takes to format code with unusual operators for the first time, i.e. if you enter `1 +++++++ ` both in the current [Ormolu Live](https://ormolu-live.tweag.io/) and the one in this PR (see https://github.com/tweag/ormolu/pull/991#issuecomment-1421285974) and then type another `1` to make this a valid expression, the version from this PR is instant, while the one from `master` has a noticeable delay (but is still pretty fast).
OTOH, this slightly increases binary sizes (all …
=> Pre-init Ormolu Live with Wizer

CHANGELOG.md, src/Ormolu/Exception.hs, src/Ormolu/Utils/Cabal.hs
When ormolu fails to parse the Cabal file the user doesn't know what is the actual error as only the cabal filepath is reported. This makes the necessary changes to actually show what errors the cabal file parser encountered.
Before:
```
Parsing this .cabal file failed:
/path/to/file.cabal
```
After:
```
Parsing this .cabal file failed:
/path/to/file.cabal:0:0: Unsupported cabal-version 3.8. See https://github.com/haskell/cabal/issues/4899.
```
Note: Removing the `Eq` instance on `OrmoluException` was the easy way to not
having to implement an orphan `Eq` instance on `PError`. This does not have
any impact elsewhere as we're actually not making use of the `Eq` instance
on this exception type.
=> Provide more context on Cabal file parsing errors

CHANGELOG.md, data/examples/declaration/data/gadt/unicode-out.hs, data/examples/declaration/data/gadt/unicode.hs, src/Ormolu/Diff/ParseResult.hs
Inspired by and alternative to #1008 (except the first commit there).
See the new example snippet for the snippet that caused errors before this PR.
Close #1008.
=> Fix false positives in AST diffing related to `UnicodeSyntax`

CHANGELOG.md, data/examples/module-header/multiline-empty-comment-out.hs, data/examples/module-header/multiline-empty-comment.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Meat/Module.hs
Closes #906, see https://github.com/tweag/ormolu/pull/933#issuecomment-1369080586 for more context. The main advantage of this PR to #933 is that it is much more minimal, bu it is still relatively ad-hoc.
There is a similar issue in other cases, e.g. also with this PR (or also with #933), comments "escape" here:
```haskell
data Foo = Foo {
-- foo
}
foo = [
-- foo
]
foo = (
-- foo
)
```
See https://github.com/tweag/ormolu/commit/54dfe3ebe3d30f4b248eba7192b400ca477c6a97 for an approach to call `encloseLocated` "automatically" via an overlapping instance, which e.g. "catches" the comment in the first case in the example above. The other two would probably need ad-hoc handling in `p_rdrName`.
=> Don't let comments escape from empty export lists

ormolu-live/app/Main.hs, ormolu-live/ormolu-live.cabal
To see the difference, paste
```haskell
import Control.Lens.Operators
wreq =
let opts = defaults & auth ?~ awsAuth AWSv4 "key" "secret"
& header "Accept" .~ ["application/json"]
& header "Runscope-Bucket-Auth" .~ ["1example-1111-4yyyy-zzzz-xxxxxxxx"]
in  getWith opts
```
both in Ormolu Live [before this PR](https://badafc04524a7c0558fbc95d4b7482bd0b83bdf9--ormolu-live.netlify.app/) as well as after this PR (see link in https://github.com/tweag/ormolu/pull/1015#issuecomment-1520591200).
=> Make all packages available for fixity inference in Ormolu Live

src/Ormolu/Parser/CommentStream.hs, src/Ormolu/Parser/Result.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Comments.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Common.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/ImportExport.hs, src/Ormolu/Printer/Meat/Module.hs, src/Ormolu/Printer/Meat/Pragma.hs
Some clean up broken out from #933
=> Clean up some stuff around comments

ormolu.cabal
`ansi-terminal-1.0` is released on Hackage.
See also https://github.com/commercialhaskell/stackage/issues/6976.
Tested by building with Stack >= 2.9.3 and `stack.yaml` with these additions:
~~~yaml
resolver: lts-20.20 # GHC 9.2.7
extra-deps:
- ansi-terminal-1.0
- ansi-terminal-types-0.11.5
allow-newer: true
allow-newer-deps:
- ansi-wl-pprint
~~~
=> Relax upper bound to accommodate dependency on `ansi-terminal-1.0`

CHANGELOG.md, README.md, app/Main.hs, extract-hackage-info/src/Hoogle.hs, fixity-tests/.ormolu, fixity-tests/default.nix, fixity-tests/test-2-input.hs, fixity-tests/test-2-no-extra-info-expected.hs, fixity-tests/test-2-with-reexports-expected.hs, flake.nix, ormolu.cabal, src/Ormolu.hs, src/Ormolu/Config.hs, src/Ormolu/Fixity.hs, src/Ormolu/Fixity/Imports.hs, src/Ormolu/Fixity/Internal.hs, src/Ormolu/Fixity/Parser.hs, src/Ormolu/Fixity/Printer.hs, src/Ormolu/Parser.hs, src/Ormolu/Utils/Fixity.hs, tests/Ormolu/Fixity/ParserSpec.hs, tests/Ormolu/Fixity/PrinterSpec.hs, tests/Ormolu/FixitySpec.hs, weeder.dhall
Close #1017.
It turns out that gaining knowledge of all module re-exports in the ecosystem is tricky because the Hoogle database does not contain this information, so one would need to download all 14+k packages from Hackage and parse their source code. We've decided that perhaps hardcoding some common re-exports and otherwise giving the users a way to make Ormolu aware of arbitrary important re-exports is a satisfactory solution for now.
=> Allow to specify module re-exports in .ormolu files

CHANGELOG.md, data/examples/declaration/value/function/lambda-case-out.hs, data/examples/declaration/value/function/lambda-case.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
=> Format `\cases` with multiple patterns across multiple lines correctly

ormolu-live/app/Main.hs, ormolu-live/ormolu-live.cabal
Since we made all packages available in Ormolu Live by default in #1015, there are some surprising discrepancies between the CLI and Ormolu Live, for example:
<table>
<tr>
<th>Input, also a fixed point in the CLI</th>
<th>
Output in <a href="https://49eb083d2b94ad882b1ff5f8b65f9870ee94a53d--ormolu-live.netlify.app/">current Ormolu Live</a>
</th>
</tr>
<tr>
<td>
```haskell
foo =
bar $
baz
```
</td>
<td>
```haskell
foo =
bar
$ baz
```
</td>
</tr>
<tr>
<td>
```haskell
-- with -p lens
import Control.Lens
foo =
bar
& a .~ 1
& b .~ 2
```
</td>
<td>
```haskell
-- with -p lens
import Control.Lens
foo =
bar
& a
.~ 1
& b
.~ 2
```
</td>
</tr>
</table>
Another example is the snippet from #1028. [With this PR](https://github.com/tweag/ormolu/pull/1029#issuecomment-1555949752), all of them are now also …
=> Ormolu Live: exclude certain packages with conflicting modules

CHANGELOG.md, src/Ormolu/Utils/Cabal.hs, tests/Ormolu/CabalInfoSpec.hs
Resolves #1032
Technically, only the first commit is necessary to solve the issue. But I refactored the `CabalInfo` subsystem to ensure that the former `CabalFileNotFound` + `CabalFileDidNotMention` branches used the same logic. Specifically, this change allows `refineConfig` to be the sole source of truth for defining the Cabal information for both a cabal file not existing and a cabal file not mentioning a source file (previously, this was two different locations: `parseCabalInfo` was doing it for `CabalFileDidNotMention` and `refineConfig` was doing it for `CabalFileNotFound`).
Add the following Haskell file:
```hs
foo =
unlines $
hello <> world : ["Line " ++ show x | x <- [10 .. 20]]
where
hello = "hello"
world = " world"
```
Running `ormolu` on it formats the same in both cases:
1. …
=> Ensure source file not mentioned in cabal file has same behavior as cabal file not existing

CHANGELOG.md, README.md, app/Main.hs, src/Ormolu.hs, src/Ormolu/Config.hs, src/Ormolu/Fixity/Imports.hs, src/Ormolu/Fixity/Internal.hs, src/Ormolu/Fixity/Parser.hs, src/Ormolu/Fixity/Printer.hs, src/Ormolu/Utils/Fixity.hs, tests/Ormolu/Fixity/ParserSpec.hs, tests/Ormolu/FixitySpec.hs, tests/Ormolu/PrinterSpec.hs
=> Support inter-package module re-exports

CHANGELOG.md, data/examples/other/necessary-brackets-out.hs, data/examples/other/necessary-brackets.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #1044 
This PR basically is a re-implementation of #767: Instead of unconditionally omitting braces for the final function argument, we set layout-based brace information in `do` blocks (statements) only for all *but* the last statement. This means that the brace information is now properly propagated in cases like #1044.
=> Preserve necessary braces for final function arguments

src/Ormolu.hs, src/Ormolu/Parser/CommentStream.hs
Make debug logs more informative + useful.
Printing out the config is useful now with the fixity + reexport configuration.
```bash
stack run -- ormolu --debug data/examples/declaration/class/associated-type-defaults.hs
```
```
Found .cabal file ormolu.cabal, but it did not mention data/examples/declaration/class/associated-type-defaults.hs
*** CONFIG *** Config {cfgDynOptions = [], cfgFixityOverrides = FixityOverrides {unFixityOverrides = fromList []}, cfgModuleReexports = ModuleReexports {unModuleReexports = fromList [(ModuleName "Control.Lens",(Just (PackageName "lens"),ModuleName "Control.Lens.At") :| [(Just (PackageName "lens"),ModuleName "Control.Lens.Cons"),(Just (PackageName "lens"),ModuleName "Control.Lens.Each"),(Just (PackageName "lens"),ModuleName "Control.Lens.Empty"),(Just …
```
=> Update debug logs

.github/workflows/ci.yml, expected-failures/Agda.txt, expected-failures/default.nix, expected-failures/esqueleto.txt, extract-hackage-info/extract-hackage-info.cabal, flake.lock, flake.nix, ormolu-live/default.nix, ormolu.cabal
Update GHC and Cabal deps; the haskell.nix bump also gives us a new nixpkgs which requires a few minor changes.
Motivated by IOG cache issues causing CI to fail in #1057
=> Update GHC and Cabal deps

flake.lock, flake.nix, ormolu-live/cabal.project, ormolu-live/default.nix
As already mentioned in #1063
This allows us to no longer depend on head.hackage which is, as a moving target due to the missing support for `index-state` ([upstream issue](https://gitlab.haskell.org/ghc/head.hackage/-/issues/53)), a source of annoying failures as mostly recently in #1063 ([logs](https://github.com/tweag/ormolu/actions/runs/6052132181/job/16425289419?pr=1063)).
=> Use WASM GHC 9.8

CHANGELOG.md, data/examples/declaration/value/function/operator-hash-with-unboxed-sums-out.hs, data/examples/declaration/value/function/operator-hash-with-unboxed-sums.hs, data/examples/declaration/value/function/operator-hash-without-unboxed-sums-out.hs, data/examples/declaration/value/function/operator-hash-without-unboxed-sums.hs, src/Ormolu/Printer/Meat/Common.hs
Closes #1062 
From https://downloads.haskell.org/ghc/9.6.2/docs/users_guide/exts/primitives.html:
> Note that when unboxed tuples are enabled, `(#` is a single lexeme, so for example when using operators like `#` and `#-` you need to write `( # )` and `( #- )` rather than `(#)` and `(#-)`.
It turns that this is already the case for `UnboxedSums` (which is implied by `UnboxedTuples`).
=> Fix interaction of operators starting with `#` and `UnboxedSums`

.gitignore
This file is typically automatically derived with [`implicit-hie`](https://hackage.haskell.org/package/implicit-hie).
=> Add hie.yaml to .gitignore

CHANGELOG.md, data/examples/other/jsffi-out.hs, data/examples/other/jsffi.hs, src/GHC/DynFlags.hs
Closes #1087 
According to the ["Split out AST and Parser libraries from GHC" Haskell Foundation tech proposal](https://github.com/Ericson2314/tech-proposals/blob/ast-parser-libs/proposals/accepted/000-ast-parser-libs.rst#proof-of-success-use-by-hlint), `parseDynamicFilePragma` (which is responsible here) is known to be in need of a refactoring to be fit for purpose as being nicely usable by external tools, so I am not going to try to change this upstream, but rather work around it for the time being, as the fix is very simple.
=> Don't error on `JavaScriptFFI` language pragma

flake.nix
Trying to access the cache results in HTTP 500 errors. `cache.iog.io` should now contain everything.
=> Remove decommissioned zw3rk cache

CHANGELOG.md, README.md, src/Ormolu.hs, src/Ormolu/Fixity/Internal.hs, src/Ormolu/Printer.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Type.hs, src/Ormolu/Printer/Operators.hs, tests/Ormolu/FixitySpec.hs, tests/Ormolu/OpTreeSpec.hs
=> Make Ormolu print debug info about operator fixity inference

ormolu.cabal
Motivation: this is blocking the reintroduction of `ansi-terminal-1.1.x` to nightly snapshots. See: https://github.com/commercialhaskell/stackage/pull/7420#issuecomment-2110842180
=> Relax upper bound to admit ansi-terminal-1.1.1

.github/workflows/binaries.yml, flake.nix
Recently, `macos-latest` [switched](https://github.com/orgs/community/discussions/102846) from `macos-12` (`x86_64`) to `macos-14` (`aarch64`, i.e. M1 ARM). The current code for building a macOS release binary only works for `x86_64-darwin`. This PR fixes that (allowing to also build on `aarch64-darwin`), and also renames the release artifacts from
- ormolu-Linux.zip
- ormolu-macOS.zip
- ormolu-Windows.zip
to the more precise
- ormolu-x86_64-linux.zip
- ormolu-aarch64-darwin.zip
- ormolu-x86_64-darwin.zip
- ormolu-x86_64-windows.zip
See https://github.com/amesgen/ormolu/releases/tag/test-release-new for an example release with this new code.
Also, we now properly sign the macOS binaries, as running `aarch64-darwin` binaries requires that.
=> Use Nix platform identifiers for release binaries

app/Main.hs, extract-hackage-info/extract-hackage-info.cabal, extract-hackage-info/src/Main.hs, ormolu.cabal, src/Ormolu.hs, src/Ormolu/Terminal.hs, src/Ormolu/Utils/Fixity.hs, src/Ormolu/Utils/IO.hs, tests/Ormolu/Diff/TextSpec.hs, tests/Ormolu/PrinterSpec.hs
A bit of easy cleanup, from the module docs:
> Efficient UTF-8 support for text I/O. Unlike `Data.Text.IO`, these functions do not depend on the locale and do not do line ending conversion.
=> Use `Data.Text.IO.Utf8` from `text-2.1`

CHANGELOG.md, data/examples/declaration/data/infix-haddocks-out.hs, data/examples/declaration/data/infix-haddocks.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs
Resolves #758. Recommend reviewing commit-by-commit
=> Fix haddocks on infix constructors

CHANGELOG.md, data/examples/declaration/class/default-signatures-out.hs, data/examples/declaration/data/gadt/multiline-out.hs, data/examples/declaration/rewrite-rule/type-signature-out.hs, data/examples/declaration/value/function/fancy-forall-0-out.hs, data/examples/declaration/value/function/fancy-forall-1-out.hs, data/examples/declaration/value/function/implicit-params-out.hs, data/examples/declaration/value/function/multiline-types-out.hs, data/examples/declaration/value/function/multiline-types.hs, data/examples/other/multiline-forall-out.hs, src/Ormolu/Printer/Meat/Type.hs
Currently, function arguments are forced to be on multiple lines if the whole type is multiline:
```hs
foo ::
Show a =>
a ->
String
```
This allows the arguments to stay on the same line if they were originally:
```hs
foo ::
Show a =>
a -> String
```
If the user wrote the function args on multiple lines, it will stay on multiple lines. So this change is not a breaking change for people with already formatted code
ref. https://github.com/fourmolu/fourmolu/pull/277 https://github.com/fourmolu/fourmolu/pull/410
=> Preserve single line function arguments

.github/workflows/ci.yml, CONTRIBUTING.md, extract-hackage-info/extract-hackage-info.cabal, fixity-tests/dummy.cabal, flake.lock, flake.nix, nix/format.sh, ormolu-live/ormolu-live.cabal, ormolu.cabal
See https://github.com/tweag/ormolu/pull/1129#issuecomment-2214104633 and https://github.com/tweag/ormolu/pull/1129#issuecomment-2215060315
=> Format `.cabal` files with cabal-gild

CHANGELOG.md, app/Main.hs, ormolu.cabal, src/Ormolu/Utils/Cabal.hs, src/Ormolu/Utils/Fixity.hs, src/Ormolu/Utils/IO.hs
Closes #1128
There is no explicit configuration for this, but it is possible for users to override by changing the RTS options to the `ormolu` executable.
=> Format files in parallel

CHANGELOG.md, data/examples/declaration/value/function/type-applications-out.hs, data/examples/declaration/value/function/type-applications.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #1134 
This PR basically reverts #616 (but keeps the tests that were added there), which was necessary back then, but no longer is due to [GHC proposal 229 ("Whitespace-sensitive operator parsing")](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0229-whitespace-bang-patterns.rst).
Concretely, the example from #613/#616
```haskell
sing @ $(symFQN name)
```
is nowadays always parsed as an application of the (value-level) operator `@` to two value-level arguments, in contrast to a type application back then (when `TypeApplications` was enabled). Hence, we don't need to handle anything specially here by inserting extra spaces.
This fixes the bug because `HsSpliceTy` is also used to represent `QuasiQuotes`.
=> Format type applications of `QuasiQuotes` correctly

data/examples/declaration/value/function/arrow/proc-form-do-indent-out.hs, data/examples/declaration/value/function/arrow/proc-form-do-indent.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Closes #1144 
We need to indent the closing parenthesis in arrow `do` blocks, just as we need to do for regular `do` blocks. We already have `BracketStyle` for that, we just need to propagate it.
=> Propagate `BracketStyle` in arrow application

CHANGELOG.md, data/examples/declaration/signature/fixity/infix-out.hs, data/examples/declaration/signature/fixity/infix.hs, src/Ormolu/Diff/ParseResult.hs
Closes #1166
The problem is that formatting `infix +` to `infix 9 +` changes the exact print annotations, namely in
```haskell
XFixSig ~ ((EpaLocation, Maybe EpaLocation), SourceText)
```
the `Maybe EpaLocation` (indicating the position of the number, if present) changes from `Nothing` to `Just`. The fix is simply to ignore this difference.
An alternative would be to preserve the input choice of whether the fixity is implicit, but I like the current behavior as it provides more consistency and explicitness.
=> Fix false positives in AST diffing with implicit fixities

CHANGELOG.md, data/examples/declaration/value/function/required-type-arguments-2-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Type.hs
Input:
```hs
typeSig ::
( Int
-> Int -> Int
)
requiredType =
f ( Int
-> Int -> Int
)
```
Current output:
```hs
typeSig ::
( Int ->
Int ->
Int
)
requiredType =
f
( Int ->
Int -> Int
)
```
After this PR:
```hs
typeSig ::
( Int ->
Int ->
Int
)
requiredType =
f
( Int ->
Int ->
Int
)
```
=> Make RequiredTypeArguments consistent with types
